package generator

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/slavkiy/witgo/parser/ir"
)

type renderer struct {
	out              bytes.Buffer
	interfaces       map[string]*ir.Interface
	records          map[string]*ir.Record
	namedTypes       map[string]any
	modelFuncs       map[string][]*ir.Func
	exports          map[string]bool
	emitted          map[string]string
	needsFmt         bool
	needsJSON        bool
	needsWitgo       bool
	needsContext     bool
	needsErrors      bool
	hasWorld         bool
	err              error
	witPackage       *ir.Package
	enableRuntimeAPI bool
	goOverlay        *GoOverlay
	goImports        map[string]bool
}

type RenderOptions struct {
	EnableRuntimeAPI bool
	GoOverlay        *GoOverlay
}

// Render converts a lowered WIT file into unformatted Go source.
func Render(file *ir.File, packageName string) ([]byte, error) {
	return RenderWithOptions(file, packageName, RenderOptions{})
}

func RenderWithOptions(file *ir.File, packageName string, options RenderOptions) ([]byte, error) {
	if file == nil {
		return nil, fmt.Errorf("IR file is nil")
	}
	if !isPackageName(packageName) {
		return nil, fmt.Errorf("invalid Go package name %q", packageName)
	}

	r := &renderer{
		interfaces:       make(map[string]*ir.Interface),
		records:          make(map[string]*ir.Record),
		namedTypes:       make(map[string]any),
		modelFuncs:       make(map[string][]*ir.Func),
		exports:          make(map[string]bool),
		emitted:          make(map[string]string),
		witPackage:       file.Package,
		enableRuntimeAPI: options.EnableRuntimeAPI,
		goOverlay:        options.GoOverlay,
		goImports:        make(map[string]bool),
	}
	if options.GoOverlay != nil {
		r.needsFmt = true
		r.needsJSON = true
		for _, mapping := range options.GoOverlay.types {
			if mapping.Config.Import != "" {
				r.goImports[mapping.Config.Import] = true
			}
		}
	}
	r.collect(file)
	if r.err != nil {
		return nil, r.err
	}

	var body bytes.Buffer
	r.out = body
	if err := r.renderFile(file); err != nil {
		return nil, err
	}
	if r.err != nil {
		return nil, r.err
	}
	body = r.out

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by witgo. DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "package %s\n", packageName)
	if r.needsFmt || r.hasWorld || r.needsJSON || r.needsWitgo || r.needsContext || r.needsErrors || len(r.goImports) > 0 {
		fmt.Fprintln(&out)
		fmt.Fprintln(&out, "import (")
		if r.hasWorld || r.needsContext {
			fmt.Fprintln(&out, `	"context"`)
		}
		if r.hasWorld || r.needsJSON {
			fmt.Fprintln(&out, `	"encoding/json"`)
		}
		if r.needsErrors {
			fmt.Fprintln(&out, `	"errors"`)
		}
		if r.needsFmt || r.hasWorld {
			fmt.Fprintln(&out, `	"fmt"`)
		}
		if r.hasWorld || r.needsWitgo {
			fmt.Fprintln(&out, `	"github.com/slavkiy/witgo"`)
		}
		imports := make([]string, 0, len(r.goImports))
		for importPath := range r.goImports {
			imports = append(imports, importPath)
		}
		sort.Strings(imports)
		for _, importPath := range imports {
			fmt.Fprintf(&out, "\t%q\n", importPath)
		}
		fmt.Fprintln(&out, ")")
	}
	fmt.Fprintln(&out)
	if file.Package != nil {
		fmt.Fprintln(&out, "const (")
		fmt.Fprintf(&out, "\tWITPackageNamespace = %s\n", strconv.Quote(file.Package.Namespace))
		fmt.Fprintf(&out, "\tWITPackageName = %s\n", strconv.Quote(file.Package.Name))
		fmt.Fprintf(&out, "\tWITPackageVersion = %s\n", strconv.Quote(file.Package.Version))
		fmt.Fprintf(&out, "\tWITPackageID = %s\n", strconv.Quote(witPackageID(file.Package)))
		fmt.Fprintln(&out, ")")
		fmt.Fprintln(&out)
	}
	if r.enableRuntimeAPI {
		r.renderRuntimeSystemFacade(&out)
	}
	if r.needsFmt {
		fmt.Fprintln(&out, "func liftValue[T any](value any) (T, error) {")
		fmt.Fprintln(&out, "\tif typed, ok := value.(T); ok {")
		fmt.Fprintln(&out, "\t\treturn typed, nil")
		fmt.Fprintln(&out, "\t}")
		fmt.Fprintln(&out, "\tdata, err := json.Marshal(value)")
		fmt.Fprintln(&out, "\tif err != nil { var zero T; return zero, fmt.Errorf(\"encode component value: %w\", err) }")
		fmt.Fprintln(&out, "\tvar result T")
		fmt.Fprintln(&out, "\tif err := json.Unmarshal(data, &result); err != nil {")
		fmt.Fprintln(&out, "\t\treturn result, fmt.Errorf(\"decode component value: %w\", err)")
		fmt.Fprintln(&out, "\t}")
		fmt.Fprintln(&out, "\treturn result, nil")
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
	}
	out.Write(body.Bytes())
	return out.Bytes(), nil
}

func (r *renderer) collect(file *ir.File) {
	for _, decl := range file.Decls {
		r.collectNamedDecl(decl)
		switch decl := decl.(type) {
		case *ir.Interface:
			r.interfaces[decl.Name] = decl
			for _, item := range decl.Items {
				r.collectNamedDecl(item)
				if record, ok := item.(*ir.Record); ok {
					r.records[record.Name] = record
				}
				r.inspectItem(item)
			}
		case *ir.Record:
			r.records[decl.Name] = decl
		case *ir.World:
			r.needsFmt = true
			r.hasWorld = true
			for _, item := range decl.Items {
				r.collectNamedDecl(item)
				r.inspectWorldItem(item)
				if export, ok := item.(*ir.Export); ok {
					if path, ok := export.Extern.(*ir.ExternPath); ok && len(path.Path.Segments) > 0 {
						r.exports[path.Path.Segments[len(path.Path.Segments)-1]] = true
					}
				}
			}
		case *ir.TypeDef:
			r.inspectType(decl.Type)
		}
	}
	for name, iface := range r.interfaces {
		if !r.exports[name] {
			continue
		}
		for _, fn := range interfaceFunctions(iface.Items) {
			if len(fn.Params) == 0 {
				continue
			}
			named, ok := fn.Params[0].Type.(*ir.NamedType)
			if ok && r.records[named.Name] != nil {
				r.modelFuncs[named.Name] = append(r.modelFuncs[named.Name], fn)
				r.needsFmt = true
			}
		}
	}
}

func (r *renderer) collectNamedDecl(decl any) {
	switch decl := decl.(type) {
	case *ir.TypeDef:
		r.namedTypes[decl.Name] = decl
	case *ir.Record:
		r.namedTypes[decl.Name] = decl
	case *ir.Flags:
		r.namedTypes[decl.Name] = decl
		r.needsJSON = true
		r.needsFmt = true
		if len(decl.Flags) > 64 && r.err == nil {
			r.err = fmt.Errorf("flags %q has %d members; maximum generated bitset size is 64", decl.Name, len(decl.Flags))
		}
	case *ir.Enum:
		r.namedTypes[decl.Name] = decl
		r.needsJSON = true
		r.needsFmt = true
	case *ir.Variant:
		r.namedTypes[decl.Name] = decl
		r.needsJSON = true
		r.needsFmt = true
	case *ir.Resource:
		r.namedTypes[decl.Name] = decl
		r.needsWitgo = true
	}
}

func (r *renderer) inspectItem(item ir.InterfaceItem) {
	switch item := item.(type) {
	case *ir.TypeDef:
		r.inspectType(item.Type)
	case *ir.Record:
		for _, field := range item.Fields {
			r.inspectType(field.Type)
		}
	case *ir.Variant:
		for _, variantCase := range item.Cases {
			r.inspectType(variantCase.Type)
		}
	case *ir.Func:
		for _, param := range item.Params {
			r.inspectType(param.Type)
		}
		r.inspectType(item.Result)
	}
}

func (r *renderer) inspectWorldItem(item ir.WorldItem) {
	switch item := item.(type) {
	case *ir.Func:
		r.inspectType(item.Result)
	case *ir.Import:
		r.inspectExtern(item.Extern)
	case *ir.Export:
		r.inspectExtern(item.Extern)
	}
}

func (r *renderer) inspectExtern(extern ir.ExternType) {
	switch extern := extern.(type) {
	case *ir.InlineInterface:
		for _, item := range extern.Items {
			r.inspectItem(item)
		}
	case *ir.FuncType:
		r.inspectType(extern.Func.Result)
	}
}

func (r *renderer) inspectType(typ ir.Type) {
	switch typ := typ.(type) {
	case *ir.PrimitiveType:
		if typ.Name == "char" {
			r.needsWitgo = true
		}
	case *ir.NamedType:
		if typ.Name == "error-context" || typ.Name == "char" {
			r.needsWitgo = true
		}
	case *ir.GenericType:
		if typ.Name == "result" || typ.Name == "option" {
			r.needsWitgo = true
		}
		if typ.Name == "borrow" || typ.Name == "own" || typ.Name == "future" || typ.Name == "stream" {
			r.needsWitgo = true
		}
		for _, arg := range typ.Args {
			r.inspectType(arg)
		}
	case *ir.TupleType:
		r.needsWitgo = true
		for _, item := range typ.Items {
			r.inspectType(item)
		}
	}
}

func (r *renderer) renderFile(file *ir.File) error {
	for _, decl := range file.Decls {
		switch decl := decl.(type) {
		case *ir.Interface:
			if err := r.renderInterfaceTypes(decl); err != nil {
				return err
			}
		case *ir.World:
			if err := r.renderWorldTypes(decl); err != nil {
				return err
			}
		default:
			if err := r.renderTypeDecl(decl); err != nil {
				return err
			}
		}
	}

	for _, decl := range file.Decls {
		if iface, ok := decl.(*ir.Interface); ok {
			if err := r.renderInterface(iface.Name, iface.Items); err != nil {
				return err
			}
		}
	}

	worldCount := 0
	for _, decl := range file.Decls {
		if _, ok := decl.(*ir.World); ok {
			worldCount++
		}
	}
	if worldCount > 0 {
		fmt.Fprintln(&r.out, "type runtimeCaller interface {")
		fmt.Fprintln(&r.out, "\tCallContext(ctx context.Context, name string, args ...any) (any, error)")
		fmt.Fprintln(&r.out, "\tClose() error")
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
	}
	for _, decl := range file.Decls {
		if world, ok := decl.(*ir.World); ok {
			if err := r.renderWorld(world); err != nil {
				return err
			}
		}
	}
	return nil
}

func (r *renderer) renderRuntimeSystemFacade(out *bytes.Buffer) {
	fmt.Fprintln(out, "// RuntimeSystem - vendor capability witgo:runtime/runtime@1.0.0.")
	fmt.Fprintln(out, "// Read-only methods expose only call-local sanitized state.")
	fmt.Fprintln(out, "type RuntimeSystem interface {")
	fmt.Fprintln(out, "\tCallInfo() (witgo.RuntimeCallInfo, error)")
	fmt.Fprintln(out, "\tFuelInfo() (witgo.RuntimeFuelInfo, error)")
	fmt.Fprintln(out, "\tLimits() (witgo.RuntimeLimits, error)")
	fmt.Fprintln(out, "\tIsCancelled() (bool, error)")
	fmt.Fprintln(out, "\t// UnsafeRequestAdditionalFuel asks host policy for a bounded grant; denial is normal.")
	fmt.Fprintln(out, "\tUnsafeRequestAdditionalFuel(amount uint64, reason string) (witgo.FuelGrant, error)")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "// System groups opt-in system capabilities available to guest plugin code.")
	fmt.Fprintln(out, "type System struct { Runtime RuntimeSystem }")
	fmt.Fprintln(out)
}

func (r *renderer) renderInterfaceTypes(iface *ir.Interface) error {
	for _, item := range iface.Items {
		if _, ok := item.(*ir.Use); ok {
			continue
		}
		if _, ok := item.(*ir.Func); ok {
			continue
		}
		if err := r.renderTypeDecl(item); err != nil {
			return fmt.Errorf("interface %q: %w", iface.Name, err)
		}
	}
	return nil
}

func (r *renderer) renderWorldTypes(world *ir.World) error {
	for _, item := range world.Items {
		switch item := item.(type) {
		case *ir.Use, *ir.Func, *ir.Import, *ir.Export, *ir.Include:
			continue
		default:
			if err := r.renderTypeDecl(item); err != nil {
				return fmt.Errorf("world %q: %w", world.Name, err)
			}
		}
	}
	return nil
}

func (r *renderer) renderTypeDecl(decl any) error {
	switch decl := decl.(type) {
	case *ir.TypeDef:
		if !r.markEmitted(decl.Name, "type") {
			return nil
		}
		if mapping, ok := r.typeMapping(decl.Name); ok {
			fmt.Fprintf(&r.out, "type %s = %s\n\n", goName(decl.Name), mapping.Config.GoType)
			r.renderMappedAliasCodec(decl, mapping)
		} else {
			fmt.Fprintf(&r.out, "type %s = %s\n\n", goName(decl.Name), r.goType(decl.Type))
		}
	case *ir.Record:
		if !r.markEmitted(decl.Name, "record") {
			return nil
		}
		r.renderRecord(decl)
	case *ir.Flags:
		if !r.markEmitted(decl.Name, "flags") {
			return nil
		}
		r.renderFlags(decl)
	case *ir.Enum:
		if !r.markEmitted(decl.Name, "enum") {
			return nil
		}
		r.renderEnum(decl)
	case *ir.Variant:
		if !r.markEmitted(decl.Name, "variant") {
			return nil
		}
		r.renderVariant(decl)
	case *ir.Resource:
		if !r.markEmitted(decl.Name, "resource") {
			return nil
		}
		r.renderResource(decl)
	case *ir.Interface, *ir.World:
		return nil
	default:
		return fmt.Errorf("unsupported declaration %T", decl)
	}
	return nil
}

func (r *renderer) markEmitted(name, kind string) bool {
	goIdentifier := goName(name)
	if previous, exists := r.emitted[goIdentifier]; exists {
		if r.err == nil {
			r.err = fmt.Errorf("Go name collision: WIT %s %q and %s both generate %q", previous, name, kind, goIdentifier)
		}
		return false
	}
	r.emitted[goIdentifier] = kind + " " + strconv.Quote(name)
	return true
}

func (r *renderer) reserveGenerated(name, origin string) {
	if previous, exists := r.emitted[name]; exists {
		if r.err == nil {
			r.err = fmt.Errorf("Go name collision: %s and generated %s both use %q", previous, origin, name)
		}
		return
	}
	r.emitted[name] = "generated " + origin
}

func (r *renderer) renderRecord(record *ir.Record) {
	name := goName(record.Name)
	fmt.Fprintf(&r.out, "type %s struct {\n", name)
	for _, field := range record.Fields {
		fmt.Fprintf(&r.out, "\t%s %s `json:%s`\n", goName(field.Name), r.goType(field.Type), strconv.Quote(field.Name))
	}
	if len(r.modelFuncs[record.Name]) > 0 {
		fmt.Fprintf(&r.out, "\tbinding %sBinding\n", goLocalName(record.Name))
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	if r.recordHasOverlay(record) {
		r.renderRecordCodec(record)
	}

	if functions := r.modelFuncs[record.Name]; len(functions) > 0 {
		fmt.Fprintf(&r.out, "type %sBinding interface {\n", goLocalName(record.Name))
		for _, fn := range functions {
			fmt.Fprintf(&r.out, "\t%s%s\n", goName(fn.Name), r.clientSignature(fn))
		}
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
		for _, fn := range functions {
			fmt.Fprintf(&r.out, "func (value %s) %s%s {\n", name, modelMethodName(record.Name, fn.Name), r.modelSignature(fn))
			fmt.Fprintln(&r.out, "\tif value.binding == nil {")
			if okType, _, mapped := r.resultErrorParts(fn); mapped && isUnitType(okType) {
				fmt.Fprintln(&r.out, `		return fmt.Errorf("model is not attached to a plugin")`)
			} else if okType, _, mapped := r.resultErrorParts(fn); mapped {
				fmt.Fprintf(&r.out, "\t\treturn %s, fmt.Errorf(%q)\n", r.zeroValue(okType), "model is not attached to a plugin")
			} else if fn.Result == nil {
				fmt.Fprintln(&r.out, `		return fmt.Errorf("model is not attached to a plugin")`)
			} else {
				fmt.Fprintf(&r.out, "\t\treturn %s, fmt.Errorf(%q)\n", r.zeroValue(fn.Result), "model is not attached to a plugin")
			}
			fmt.Fprintln(&r.out, "\t}")
			args := []string{"ctx", "value"}
			for index, param := range fn.Params[1:] {
				args = append(args, paramName(param, index+1))
			}
			fmt.Fprintf(&r.out, "\treturn value.binding.%s(%s)\n", goName(fn.Name), strings.Join(args, ", "))
			fmt.Fprintln(&r.out, "}")
			fmt.Fprintln(&r.out)
		}
	}

}

func (r *renderer) renderFlags(flags *ir.Flags) {
	name := goName(flags.Name)
	local := goLocalName(flags.Name)
	r.reserveGenerated("Parse"+name, "flags parser for "+strconv.Quote(flags.Name))
	fmt.Fprintf(&r.out, "type %s uint64\n\n", name)
	fmt.Fprintln(&r.out, "const (")
	for index, flag := range flags.Flags {
		fmt.Fprintf(&r.out, "\t%s%s %s = 1 << %d\n", name, goName(flag), name, index)
	}
	fmt.Fprintln(&r.out, ")")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "const %sKnown %s = ", local, name)
	if len(flags.Flags) == 0 {
		fmt.Fprintln(&r.out, "0")
	} else {
		parts := make([]string, 0, len(flags.Flags))
		for _, flag := range flags.Flags {
			parts = append(parts, name+goName(flag))
		}
		fmt.Fprintln(&r.out, strings.Join(parts, " | "))
	}
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (value %s) Valid() bool { return value &^ %sKnown == 0 }\n", name, local)
	fmt.Fprintf(&r.out, "func (value %s) Has(flags %s) bool { return flags != 0 && flags.Valid() && value&flags == flags }\n", name, name)
	fmt.Fprintf(&r.out, "func (value *%s) Add(flags ...%s) { for _, flag := range flags { *value |= flag } }\n", name, name)
	fmt.Fprintf(&r.out, "func (value *%s) Remove(flags ...%s) { for _, flag := range flags { *value &^= flag } }\n", name, name)
	fmt.Fprintf(&r.out, "func (value %s) Names() ([]string, error) {\n", name)
	fmt.Fprintf(&r.out, "\tif !value.Valid() { return nil, fmt.Errorf(%q, value &^ %sKnown) }\n", "flags contain unknown bits: %d", local)
	fmt.Fprintln(&r.out, "\tnames := make([]string, 0)")
	for _, flag := range flags.Flags {
		fmt.Fprintf(&r.out, "\tif value&%s%s != 0 { names = append(names, %s) }\n", name, goName(flag), strconv.Quote(flag))
	}
	fmt.Fprintln(&r.out, "\treturn names, nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Parse%s(names ...string) (%s, error) {\n", name, name)
	fmt.Fprintf(&r.out, "\tvar result %s\n", name)
	fmt.Fprintln(&r.out, "\tfor _, flag := range names { switch flag {")
	for _, flag := range flags.Flags {
		fmt.Fprintf(&r.out, "\tcase %s: result |= %s%s\n", strconv.Quote(flag), name, goName(flag))
	}
	fmt.Fprintf(&r.out, "%s\n", "\tdefault: return 0, fmt.Errorf(\"unknown flag %q\", flag)")
	fmt.Fprintln(&r.out, "\t} }")
	fmt.Fprintln(&r.out, "\treturn result, nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (value %s) MarshalJSON() ([]byte, error) {\n", name)
	fmt.Fprintln(&r.out, "\tnames, err := value.Names()")
	fmt.Fprintln(&r.out, "\tif err != nil { return nil, err }")
	fmt.Fprintln(&r.out, "\treturn json.Marshal(names)")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (value *%s) UnmarshalJSON(data []byte) error {\n", name)
	fmt.Fprintln(&r.out, "\tif value == nil { return fmt.Errorf(\"cannot decode flags into nil receiver\") }")
	fmt.Fprintln(&r.out, "\tvar names []string")
	fmt.Fprintln(&r.out, "\tif err := json.Unmarshal(data, &names); err != nil { return err }")
	fmt.Fprintf(&r.out, "\tresult, err := Parse%s(names...)\n", name)
	fmt.Fprintln(&r.out, "\tif err != nil { return err }")
	fmt.Fprintln(&r.out, "\t*value = result")
	fmt.Fprintln(&r.out, "\treturn nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
}

func (r *renderer) renderEnum(enum *ir.Enum) {
	name := goName(enum.Name)
	r.reserveGenerated("Parse"+name, "enum parser for "+strconv.Quote(enum.Name))
	r.reserveGenerated(name+"Values", "enum values helper for "+strconv.Quote(enum.Name))
	fmt.Fprintf(&r.out, "type %s string\n\n", name)
	fmt.Fprintln(&r.out, "const (")
	for _, enumCase := range enum.Cases {
		fmt.Fprintf(&r.out, "\t%s%s %s = %s\n", name, goName(enumCase), name, strconv.Quote(enumCase))
	}
	fmt.Fprintln(&r.out, ")")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (value %s) String() string { return string(value) }\n", name)
	fmt.Fprintf(&r.out, "func (value %s) Valid() bool {\n\tswitch value {\n", name)
	if len(enum.Cases) > 0 {
		cases := make([]string, 0, len(enum.Cases))
		for _, enumCase := range enum.Cases {
			cases = append(cases, name+goName(enumCase))
		}
		fmt.Fprintf(&r.out, "\tcase %s: return true\n", strings.Join(cases, ", "))
	}
	fmt.Fprintln(&r.out, "\tdefault: return false\n\t}\n}")
	fmt.Fprintf(&r.out, "func Parse%s(value string) (%s, error) {\n", name, name)
	fmt.Fprintf(&r.out, "\tresult := %s(value)\n", name)
	fmt.Fprintf(&r.out, "\tif !result.Valid() { return \"\", fmt.Errorf(%q, value) }\n", "unknown "+enum.Name+" value %q")
	fmt.Fprintln(&r.out, "\treturn result, nil\n}")
	fmt.Fprintf(&r.out, "func %sValues() []%s { return []%s{", name, name, name)
	for index, enumCase := range enum.Cases {
		if index > 0 {
			fmt.Fprint(&r.out, ", ")
		}
		fmt.Fprint(&r.out, name+goName(enumCase))
	}
	fmt.Fprintln(&r.out, "} }")
	fmt.Fprintf(&r.out, "func (value %s) MarshalJSON() ([]byte, error) { if !value.Valid() { return nil, fmt.Errorf(%q, value) }; return json.Marshal(string(value)) }\n", name, "unknown "+enum.Name+" value %q")
	fmt.Fprintf(&r.out, "func (value *%s) UnmarshalJSON(data []byte) error { if value == nil { return fmt.Errorf(\"cannot decode enum into nil receiver\") }; var text string; if err := json.Unmarshal(data, &text); err != nil { return err }; result, err := Parse%s(text); if err != nil { return err }; *value = result; return nil }\n", name, name)
	fmt.Fprintln(&r.out)
}

func (r *renderer) renderVariant(variant *ir.Variant) {
	name := goName(variant.Name)
	for _, variantCase := range variant.Cases {
		r.reserveGenerated("New"+name+goName(variantCase.Name), "variant constructor for "+strconv.Quote(variant.Name+"."+variantCase.Name))
	}
	fmt.Fprintf(&r.out, "type %sKind uint32\n\n", name)
	fmt.Fprintln(&r.out, "const (")
	for index, variantCase := range variant.Cases {
		fmt.Fprintf(&r.out, "\t%sKind%s %sKind = %d\n", name, goName(variantCase.Name), name, index)
	}
	fmt.Fprintln(&r.out, ")")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "type %s struct {\n\tKind %sKind `json:%s`\n", name, name, strconv.Quote("kind"))
	for _, variantCase := range variant.Cases {
		if variantCase.Type != nil {
			fmt.Fprintf(&r.out, "\t%s *%s `json:%s`\n", goName(variantCase.Name), r.goType(variantCase.Type), strconv.Quote(variantCase.Name+",omitempty"))
		}
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	for _, variantCase := range variant.Cases {
		caseName := goName(variantCase.Name)
		if variantCase.Type == nil {
			fmt.Fprintf(&r.out, "func New%s%s() %s { return %s{Kind: %sKind%s} }\n", name, caseName, name, name, name, caseName)
		} else {
			fmt.Fprintf(&r.out, "func New%s%s(payload %s) %s { return %s{Kind: %sKind%s, %s: &payload} }\n", name, caseName, r.goType(variantCase.Type), name, name, name, caseName, caseName)
			fmt.Fprintf(&r.out, "func (value %s) Get%s() (%s, bool) { if value.Kind != %sKind%s || value.%s == nil { var zero %s; return zero, false }; return *value.%s, true }\n", name, caseName, r.goType(variantCase.Type), name, caseName, caseName, r.goType(variantCase.Type), caseName)
		}
		fmt.Fprintf(&r.out, "func (value %s) Is%s() bool { return value.Kind == %sKind%s }\n", name, caseName, name, caseName)
	}
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "func (value %s) MarshalJSON() ([]byte, error) {\n", name)
	fmt.Fprintln(&r.out, "\tswitch value.Kind {")
	for _, variantCase := range variant.Cases {
		fmt.Fprintf(&r.out, "\tcase %sKind%s:\n", name, goName(variantCase.Name))
		if variantCase.Type == nil {
			fmt.Fprintf(&r.out, "\t\treturn json.Marshal(struct { Case string `json:%s` }{Case: %s})\n", strconv.Quote("case"), strconv.Quote(variantCase.Name))
		} else {
			fmt.Fprintf(&r.out, "\t\tif value.%s == nil { return nil, fmt.Errorf(%q) }\n", goName(variantCase.Name), "variant "+variant.Name+" case "+variantCase.Name+" has nil payload")
			fmt.Fprintf(&r.out, "\t\treturn json.Marshal(struct { Case string `json:%s`; Value any `json:%s` }{Case: %s, Value: *value.%s})\n", strconv.Quote("case"), strconv.Quote("value"), strconv.Quote(variantCase.Name), goName(variantCase.Name))
		}
	}
	fmt.Fprintln(&r.out, "\tdefault:")
	fmt.Fprintf(&r.out, "\t\treturn nil, fmt.Errorf(%q, value.Kind)\n", "variant "+variant.Name+" has invalid kind %d")
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "func (value *%s) UnmarshalJSON(data []byte) error {\n", name)
	fmt.Fprintln(&r.out, "\tif value == nil { return fmt.Errorf(\"cannot decode variant into nil receiver\") }")
	fmt.Fprintln(&r.out, "\tvar envelope struct { Case string `json:\"case\"`; Value json.RawMessage `json:\"value\"` }")
	fmt.Fprintln(&r.out, "\tif err := json.Unmarshal(data, &envelope); err != nil { return err }")
	fmt.Fprintln(&r.out, "\tswitch envelope.Case {")
	for _, variantCase := range variant.Cases {
		fmt.Fprintf(&r.out, "\tcase %s:\n", strconv.Quote(variantCase.Name))
		fmt.Fprintf(&r.out, "\t\t*value = %s{Kind: %sKind%s}\n", name, name, goName(variantCase.Name))
		if variantCase.Type != nil {
			fmt.Fprintf(&r.out, "\t\tvar payload %s\n", r.goType(variantCase.Type))
			fmt.Fprintln(&r.out, "\t\tif err := json.Unmarshal(envelope.Value, &payload); err != nil { return err }")
			fmt.Fprintf(&r.out, "\t\tvalue.%s = &payload\n", goName(variantCase.Name))
		}
		fmt.Fprintln(&r.out, "\t\treturn nil")
	}
	fmt.Fprintln(&r.out, "\tdefault:")
	fmt.Fprintf(&r.out, "\t\treturn fmt.Errorf(%q, envelope.Case)\n", "variant "+variant.Name+" has unknown case %q")
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
}

func (r *renderer) renderResource(resource *ir.Resource) {
	fmt.Fprintf(&r.out, "type %s = witgo.Handle\n", goName(resource.Name))
	fmt.Fprintln(&r.out)
}

func (r *renderer) renderInterface(name string, items []ir.InterfaceItem) error {
	var functions []*ir.Func
	for _, item := range items {
		if fn, ok := item.(*ir.Func); ok {
			functions = append(functions, fn)
		}
	}
	if len(functions) == 0 {
		return nil
	}
	if !r.markEmitted(name, "interface") {
		return nil
	}
	interfaceName := goName(name)
	fmt.Fprintf(&r.out, "type %s interface {\n", interfaceName)
	for _, fn := range functions {
		fmt.Fprintf(&r.out, "\t%s%s\n", goName(fn.Name), r.clientSignature(fn))
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	r.renderInterfaceProvider(name, interfaceName, functions)
	return nil
}

func (r *renderer) renderInterfaceProvider(witName, interfaceName string, functions []*ir.Func) {
	descriptorName := interfaceName + "Descriptor"
	clientName := interfaceName + "ProviderClient"
	for _, generated := range []string{descriptorName, clientName, "Register" + interfaceName, "Resolve" + interfaceName, "AutoResolve" + interfaceName, "MustResolve" + interfaceName} {
		r.reserveGenerated(generated, "composition API for "+strconv.Quote(witName))
	}
	interfaceID := r.interfaceID(witName)
	fmt.Fprintf(&r.out, "var %s = witgo.InterfaceDescriptor{\n", descriptorName)
	fmt.Fprintf(&r.out, "\tID: %s,\n", strconv.Quote(interfaceID))
	fmt.Fprintln(&r.out, "\tFunctions: map[string]string{")
	for _, fn := range functions {
		fmt.Fprintf(&r.out, "\t\t%s: %s,\n", strconv.Quote(fn.Name), strconv.Quote(r.contractTypeSignature(fn)))
	}
	fmt.Fprintln(&r.out, "\t},")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "type %s struct { handle *witgo.ProviderHandle }\n\n", clientName)
	fmt.Fprintf(&r.out, "var _ %s = (*%s)(nil)\n\n", interfaceName, clientName)
	fmt.Fprintf(&r.out, "func (c *%s) witgoCompositionPlug() (witgo.CompositionPlug, bool) {\n", clientName)
	fmt.Fprintln(&r.out, "\tif c == nil || c.handle == nil { return witgo.CompositionPlug{}, false }")
	fmt.Fprintln(&r.out, "\treturn c.handle.CompositionPlug()")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (c *%s) witgoComponentComposition() witgo.ComponentComposition {\n", clientName)
	fmt.Fprintln(&r.out, "\tplug, ok := c.witgoCompositionPlug()")
	fmt.Fprintln(&r.out, "\tif !ok { return witgo.ComponentComposition{} }")
	fmt.Fprintln(&r.out, "\treturn witgo.ComponentComposition{Component: plug.Component, Dependencies: plug.Dependencies}")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Register%s(host *witgo.Host, name string, provider %s, options ...witgo.RegisterOption) error {\n", interfaceName, interfaceName)
	fmt.Fprintln(&r.out, "\tif host == nil { return fmt.Errorf(\"host is nil\") }")
	fmt.Fprintln(&r.out, "\tif provider == nil { return fmt.Errorf(\"provider is nil\") }")
	fmt.Fprintln(&r.out, "\tif source, ok := provider.(interface{ witgoComponentComposition() witgo.ComponentComposition }); ok {")
	fmt.Fprintln(&r.out, "\t\tcomposition := source.witgoComponentComposition()")
	fmt.Fprintf(&r.out, "\t\tif composition.Component == \"\" && witgo.DescriptorUsesRuntimeHandles(%s) { return witgo.ErrCrossRuntimeHandle }\n", descriptorName)
	fmt.Fprintln(&r.out, "\t\tif composition.Component != \"\" { options = append(options, witgo.ComponentProvider(composition)) }")
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintln(&r.out, "\tif health, ok := provider.(interface{ witgoProviderHealth() error }); ok { if err := health.witgoProviderHealth(); err != nil { return err } }")
	fmt.Fprintf(&r.out, "\t_, err := host.RegisterProvider(name, %s, func(ctx context.Context, function string, args []any) (any, error) {\n", descriptorName)
	fmt.Fprintln(&r.out, "\t\tif health, ok := provider.(interface{ witgoProviderHealth() error }); ok { if err := health.witgoProviderHealth(); err != nil { return nil, err } }")
	fmt.Fprintln(&r.out, "\t\tswitch function {")
	for _, fn := range functions {
		fmt.Fprintf(&r.out, "\t\tcase %s:\n", strconv.Quote(fn.Name))
		fmt.Fprintf(&r.out, "\t\t\tif len(args) != %d { return nil, fmt.Errorf(%q, len(args)) }\n", len(fn.Params), "provider "+interfaceID+"#"+fn.Name+" received %d arguments")
		callArgs := []string{"ctx"}
		for index, param := range fn.Params {
			arg := fmt.Sprintf("_witgoArg%d", index)
			fmt.Fprintf(&r.out, "\t\t\t%s, err := %s\n", arg, r.liftRuntimeExpr("nil", fmt.Sprintf("args[%d]", index), param.Type))
			fmt.Fprintln(&r.out, "\t\t\tif err != nil { return nil, err }")
			callArgs = append(callArgs, arg)
		}
		call := "provider." + goName(fn.Name) + "(" + strings.Join(callArgs, ", ") + ")"
		if _, _, mapped := r.resultErrorParts(fn); mapped {
			r.renderResultErrorProvider("\t\t\t", call, fn)
		} else if fn.Result == nil {
			fmt.Fprintf(&r.out, "\t\t\treturn nil, %s\n", call)
		} else if conversion, ok := r.conversionName(fn.Result); ok {
			fmt.Fprintf(&r.out, "\t\t\t_witgoResult, err := %s\n", call)
			fmt.Fprintln(&r.out, "\t\t\tif err != nil { return nil, err }")
			fmt.Fprintf(&r.out, "\t\t\treturn lower%s(_witgoResult), nil\n", conversion)
		} else {
			fmt.Fprintf(&r.out, "\t\t\treturn %s\n", call)
		}
	}
	fmt.Fprintln(&r.out, "\t\tdefault:")
	fmt.Fprintf(&r.out, "\t\t\treturn nil, fmt.Errorf(%q, function)\n", "unknown provider function "+interfaceID+"#%s")
	fmt.Fprintln(&r.out, "\t\t}")
	fmt.Fprintln(&r.out, "\t}, options...)")
	fmt.Fprintln(&r.out, "\treturn err")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "func Resolve%s(host *witgo.Host, name string) (%s, error) {\n", interfaceName, interfaceName)
	fmt.Fprintln(&r.out, "\tif host == nil { return nil, fmt.Errorf(\"host is nil\") }")
	fmt.Fprintf(&r.out, "\thandle, err := host.ResolveProvider(name, %s)\n", descriptorName)
	fmt.Fprintln(&r.out, "\tif err != nil { return nil, err }")
	fmt.Fprintf(&r.out, "\treturn &%s{handle: handle}, nil\n", clientName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func AutoResolve%s(host *witgo.Host) (%s, error) {\n", interfaceName, interfaceName)
	fmt.Fprintln(&r.out, "\tif host == nil { return nil, fmt.Errorf(\"host is nil\") }")
	fmt.Fprintf(&r.out, "\thandle, err := host.AutoResolveProvider(%s)\n", descriptorName)
	fmt.Fprintln(&r.out, "\tif err != nil { return nil, err }")
	fmt.Fprintf(&r.out, "\treturn &%s{handle: handle}, nil\n", clientName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func MustResolve%s(host *witgo.Host, name string) %s {\n", interfaceName, interfaceName)
	fmt.Fprintf(&r.out, "\tprovider, err := Resolve%s(host, name)\n", interfaceName)
	fmt.Fprintln(&r.out, "\tif err != nil { panic(err) }")
	fmt.Fprintln(&r.out, "\treturn provider")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	for _, fn := range functions {
		fmt.Fprintf(&r.out, "func (c *%s) %s%s {\n", clientName, goName(fn.Name), r.clientSignature(fn))
		args := make([]string, 0, len(fn.Params))
		for index, param := range fn.Params {
			args = append(args, r.lowerExpr(paramName(param, index), param.Type))
		}
		if fn.Result == nil {
			fmt.Fprintf(&r.out, "\t_, _witgoErr := c.handle.CallContext(ctx, %q, %q", "", fn.Name)
			for _, arg := range args {
				fmt.Fprintf(&r.out, ", %s", arg)
			}
			fmt.Fprintln(&r.out, ")")
			fmt.Fprintln(&r.out, "\treturn _witgoErr")
		} else {
			fmt.Fprintf(&r.out, "\t_witgoValue, _witgoErr := c.handle.CallContext(ctx, %q, %q", "", fn.Name)
			for _, arg := range args {
				fmt.Fprintf(&r.out, ", %s", arg)
			}
			fmt.Fprintln(&r.out, ")")
			if _, _, mapped := r.resultErrorParts(fn); mapped {
				r.renderResultErrorClient("\t", "_witgoValue", fn)
			} else {
				fmt.Fprintf(&r.out, "\tif _witgoErr != nil { return %s, _witgoErr }\n", r.zeroValue(fn.Result))
				fmt.Fprintf(&r.out, "\t_witgoResult, _witgoErr := %s\n", r.liftRuntimeExpr("nil", "_witgoValue", fn.Result))
				fmt.Fprintf(&r.out, "\tif _witgoErr != nil { return %s, _witgoErr }\n", r.zeroValue(fn.Result))
				fmt.Fprintln(&r.out, "\treturn _witgoResult, nil")
			}
		}
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
	}
}

func (r *renderer) renderWorld(world *ir.World) error {
	imports, exports, directFunctions, err := r.worldParts(world)
	if err != nil {
		return err
	}
	worldName := goName(world.Name)
	for _, generated := range []string{
		worldName, worldName + "Imports", worldName + "Bindings", worldName + "Ping",
		"AutoBind" + worldName,
		"Validate" + worldName, "Validate" + worldName + "Context",
		"Validate" + worldName + "WithOptions", "Validate" + worldName + "WithOptionsContext",
		"Check" + worldName, "Check" + worldName + "Context",
		"Check" + worldName + "WithOptions", "Check" + worldName + "WithOptionsContext",
		"Open" + worldName, "Open" + worldName + "Context",
		"Open" + worldName + "WithOptions", "Open" + worldName + "WithOptionsContext",
		"Open" + worldName + "WithHost", "Open" + worldName + "WithHostContext",
		"Open" + worldName + "WithHostOptionsContext",
		"Open" + worldName + "AutoBoundWithHost", "Open" + worldName + "AutoBoundWithHostContext",
	} {
		r.reserveGenerated(generated, "world API for "+strconv.Quote(world.Name))
	}

	fmt.Fprintf(&r.out, "// %sImports contains all host capabilities required by %s.\n", worldName, worldName)
	fmt.Fprintf(&r.out, "type %sImports struct {\n", worldName)
	for _, imported := range imports {
		fmt.Fprintf(&r.out, "\t%s %s\n", goName(imported.name), imported.interfaceName)
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "// %sBindings is the typed dependency set used for Go and plugin providers.\n", worldName)
	fmt.Fprintf(&r.out, "type %sBindings = %sImports\n\n", worldName, worldName)
	fmt.Fprintf(&r.out, "// AutoBind%s resolves every dependency when exactly one compatible provider is registered.\n", worldName)
	fmt.Fprintf(&r.out, "func AutoBind%s(host *witgo.Host) (%sBindings, error) {\n", worldName, worldName)
	fmt.Fprintf(&r.out, "\tvar bindings %sBindings\n", worldName)
	fmt.Fprintln(&r.out, "\tif host == nil { return bindings, fmt.Errorf(\"host is nil\") }")
	for index, imported := range imports {
		variable := fmt.Sprintf("_witgoProvider%d", index)
		fmt.Fprintf(&r.out, "\t%s, err := AutoResolve%s(host)\n", variable, imported.interfaceName)
		fmt.Fprintln(&r.out, "\tif err != nil { return bindings, err }")
		fmt.Fprintf(&r.out, "\tbindings.%s = %s\n", goName(imported.name), variable)
	}
	fmt.Fprintln(&r.out, "\treturn bindings, nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// %sPing returns the generated host and plugin function manifest.\n", worldName)
	fmt.Fprintf(&r.out, "func %sPing() witgo.Contract {\n", worldName)
	fmt.Fprintln(&r.out, "\treturn witgo.Contract{")
	r.renderFunctionNames("Imports", contractFunctionNames(imports, nil))
	r.renderFunctionNames("Exports", contractFunctionNames(exports, directFunctions))
	r.renderFunctionSignatures(contractFunctionSignatures(r, imports, nil), contractFunctionSignatures(r, exports, directFunctions))
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// Validate%s inspects a component without instantiating it or running guest code.\n", worldName)
	fmt.Fprintf(&r.out, "func Validate%s(filename string) (witgo.ValidationReport, error) {\n", worldName)
	fmt.Fprintf(&r.out, "\treturn Validate%sContext(context.Background(), filename)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Validate%sContext(ctx context.Context, filename string) (witgo.ValidationReport, error) {\n", worldName)
	fmt.Fprintf(&r.out, "\treturn witgo.ValidateComponentContext(ctx, filename, %sPing())\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// Validate%sWithOptions is Validate%s with explicit bridge options.\n", worldName, worldName)
	fmt.Fprintf(&r.out, "func Validate%sWithOptions(filename string, options witgo.RuntimeOptions) (witgo.ValidationReport, error) {\n", worldName)
	fmt.Fprintf(&r.out, "\treturn Validate%sWithOptionsContext(context.Background(), filename, options)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Validate%sWithOptionsContext(ctx context.Context, filename string, options witgo.RuntimeOptions) (witgo.ValidationReport, error) {\n", worldName)
	fmt.Fprintf(&r.out, "\treturn witgo.ValidateComponentWithOptionsContext(ctx, filename, options, %sPing())\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// Check%s validates a component and returns ErrContractMismatch when it is incompatible.\n", worldName)
	fmt.Fprintf(&r.out, "func Check%s(filename string) error {\n", worldName)
	fmt.Fprintf(&r.out, "\treturn Check%sContext(context.Background(), filename)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Check%sContext(ctx context.Context, filename string) error {\n", worldName)
	fmt.Fprintf(&r.out, "\treport, err := Validate%sContext(ctx, filename)\n", worldName)
	fmt.Fprintln(&r.out, "\tif err != nil { return err }")
	fmt.Fprintln(&r.out, "\treturn report.Err()")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// Check%sWithOptions is Check%s with explicit bridge options.\n", worldName, worldName)
	fmt.Fprintf(&r.out, "func Check%sWithOptions(filename string, options witgo.RuntimeOptions) error {\n", worldName)
	fmt.Fprintf(&r.out, "\treturn Check%sWithOptionsContext(context.Background(), filename, options)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Check%sWithOptionsContext(ctx context.Context, filename string, options witgo.RuntimeOptions) error {\n", worldName)
	fmt.Fprintf(&r.out, "\treport, err := Validate%sWithOptionsContext(ctx, filename, options)\n", worldName)
	fmt.Fprintln(&r.out, "\tif err != nil { return err }")
	fmt.Fprintln(&r.out, "\treturn report.Err()")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// %s is a client for the %s WIT world.\n", worldName, world.Name)
	fmt.Fprintf(&r.out, "type %s struct {\n", worldName)
	fmt.Fprintln(&r.out, "\truntime runtimeCaller")
	fmt.Fprintln(&r.out, "\treopen func(context.Context) (runtimeCaller, error)")
	for _, export := range exports {
		fmt.Fprintf(&r.out, "\t%sClient *%s\n", goLocalName(export.name), export.clientName(worldName))
	}
	for _, export := range exports {
		fmt.Fprintf(&r.out, "\t%s %s\n", goName(export.name), export.interfaceName)
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (c *%s) setRuntime(runtime runtimeCaller) {\n", worldName)
	fmt.Fprintln(&r.out, "\tc.runtime = runtime")
	for _, export := range exports {
		fmt.Fprintf(&r.out, "\tif c.%sClient != nil { c.%sClient.runtime = runtime }\n", goLocalName(export.name), goLocalName(export.name))
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (c *%s) Close() error {\n", worldName)
	fmt.Fprintln(&r.out, "\tif c == nil || c.runtime == nil { return nil }")
	fmt.Fprintln(&r.out, "\treturn c.runtime.Close()")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (c *%s) Restart() error {\n", worldName)
	fmt.Fprintf(&r.out, "\treturn c.RestartContext(context.Background())\n")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (c *%s) RestartContext(ctx context.Context) error {\n", worldName)
	fmt.Fprintln(&r.out, "\tif c == nil { return fmt.Errorf(\"plugin is nil\") }")
	fmt.Fprintln(&r.out, "\tif c.reopen == nil { return fmt.Errorf(\"plugin cannot be restarted\") }")
	fmt.Fprintln(&r.out, "\tif ctx == nil { return fmt.Errorf(\"context is nil\") }")
	fmt.Fprintln(&r.out, "\t_witgoNewRuntime, err := c.reopen(ctx)")
	fmt.Fprintln(&r.out, "\tif err != nil { return err }")
	fmt.Fprintln(&r.out, "\t_witgoOldRuntime := c.runtime")
	fmt.Fprintln(&r.out, "\tc.setRuntime(_witgoNewRuntime)")
	fmt.Fprintln(&r.out, "\tif _witgoOldRuntime == nil { return nil }")
	fmt.Fprintln(&r.out, "\tif err := _witgoOldRuntime.Close(); err != nil {")
	fmt.Fprintln(&r.out, "\t\treturn fmt.Errorf(\"close previous plugin runtime: %w\", err)")
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintln(&r.out, "\treturn nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// Open%sWithHost opens a component attached to a shared composition host.\n", worldName)
	fmt.Fprintf(&r.out, "func Open%sWithHost(host *witgo.Host, filename string, bindings ...%sBindings) (*%s, error) {\n", worldName, worldName, worldName)
	fmt.Fprintf(&r.out, "\treturn Open%sWithHostContext(context.Background(), host, filename, bindings...)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Open%sWithHostContext(ctx context.Context, host *witgo.Host, filename string, bindings ...%sBindings) (*%s, error) {\n", worldName, worldName, worldName)
	fmt.Fprintf(&r.out, "\treturn Open%sWithHostOptionsContext(ctx, host, filename, witgo.RuntimeOptions{}, bindings...)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Open%sAutoBoundWithHost(host *witgo.Host, filename string) (*%s, error) {\n", worldName, worldName)
	fmt.Fprintf(&r.out, "\treturn Open%sAutoBoundWithHostContext(context.Background(), host, filename)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Open%sAutoBoundWithHostContext(ctx context.Context, host *witgo.Host, filename string) (*%s, error) {\n", worldName, worldName)
	fmt.Fprintf(&r.out, "\tbindings, err := AutoBind%s(host)\n", worldName)
	fmt.Fprintln(&r.out, "\tif err != nil { return nil, err }")
	fmt.Fprintf(&r.out, "\treturn Open%sWithHostContext(ctx, host, filename, bindings)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func Open%sWithHostOptionsContext(ctx context.Context, host *witgo.Host, filename string, options witgo.RuntimeOptions, bindings ...%sBindings) (*%s, error) {\n", worldName, worldName, worldName)
	fmt.Fprintln(&r.out, "\tif host == nil { return nil, fmt.Errorf(\"host is nil\") }")
	fmt.Fprintln(&r.out, "\toptions.CompositionHost = host")
	fmt.Fprintf(&r.out, "\treturn Open%sWithOptionsContext(ctx, filename, options, bindings...)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	for _, export := range exports {
		fmt.Fprintf(&r.out, "type %s struct {\n", export.clientName(worldName))
		fmt.Fprintln(&r.out, "\truntime runtimeCaller")
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
		fmt.Fprintf(&r.out, "func (c *%s) witgoProviderHealth() error {\n", export.clientName(worldName))
		fmt.Fprintln(&r.out, "\tif c == nil || c.runtime == nil { return witgo.ErrPluginProviderClosed }")
		fmt.Fprintln(&r.out, "\tif state, ok := c.runtime.(interface{ IsClosed() bool }); ok && state.IsClosed() { return witgo.ErrPluginProviderClosed }")
		fmt.Fprintln(&r.out, "\treturn nil")
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
		fmt.Fprintf(&r.out, "func (*%s) witgoPluginRuntimeProvider() {}\n\n", export.clientName(worldName))
		fmt.Fprintf(&r.out, "func (c *%s) witgoComponentComposition() witgo.ComponentComposition {\n", export.clientName(worldName))
		fmt.Fprintln(&r.out, "\tif c == nil || c.runtime == nil { return witgo.ComponentComposition{} }")
		fmt.Fprintln(&r.out, "\tif source, ok := c.runtime.(interface{ Composition() witgo.ComponentComposition }); ok { return source.Composition() }")
		fmt.Fprintln(&r.out, "\treturn witgo.ComponentComposition{}")
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
		fmt.Fprintf(&r.out, "func (c *%s) witgoCompositionPlug() (witgo.CompositionPlug, bool) {\n", export.clientName(worldName))
		fmt.Fprintln(&r.out, "\tcomposition := c.witgoComponentComposition()")
		fmt.Fprintln(&r.out, "\tif composition.Component == \"\" { return witgo.CompositionPlug{}, false }")
		fmt.Fprintf(&r.out, "\treturn witgo.CompositionPlug{Interface: %s, Component: composition.Component, Dependencies: composition.Dependencies}, true\n", strconv.Quote(export.callName))
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
	}

	fmt.Fprintf(&r.out, "// Open%s loads a component using the generated contract.\n", worldName)
	fmt.Fprintf(&r.out, "func Open%s(filename string, imports ...%sImports) (*%s, error) {\n", worldName, worldName, worldName)
	fmt.Fprintf(&r.out, "\treturn Open%sContext(context.Background(), filename, imports...)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// Open%sContext loads a component and propagates cancellation during startup.\n", worldName)
	fmt.Fprintf(&r.out, "func Open%sContext(ctx context.Context, filename string, imports ...%sImports) (*%s, error) {\n", worldName, worldName, worldName)
	fmt.Fprintf(&r.out, "\treturn Open%sWithOptionsContext(ctx, filename, witgo.RuntimeOptions{}, imports...)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// Open%sWithOptions loads a component with runtime options and verifies its function manifest.\n", worldName)
	fmt.Fprintf(&r.out, "func Open%sWithOptions(filename string, _witgoOptions witgo.RuntimeOptions, imports ...%sImports) (*%s, error) {\n", worldName, worldName, worldName)
	fmt.Fprintf(&r.out, "\treturn Open%sWithOptionsContext(context.Background(), filename, _witgoOptions, imports...)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "// Open%sWithOptionsContext loads a component with context and runtime options.\n", worldName)
	fmt.Fprintf(&r.out, "func Open%sWithOptionsContext(ctx context.Context, filename string, _witgoOptions witgo.RuntimeOptions, _witgoImportSets ...%sImports) (*%s, error) {\n", worldName, worldName, worldName)
	fmt.Fprintln(&r.out, "\tif ctx == nil { return nil, fmt.Errorf(\"context is nil\") }")
	if r.enableRuntimeAPI {
		fmt.Fprintln(&r.out, "\t_witgoOptions.EnableRuntimeAPI = true")
	}
	fmt.Fprintln(&r.out, "\tif len(_witgoImportSets) > 1 { return nil, fmt.Errorf(\"at most one imports value is allowed\") }")
	fmt.Fprintf(&r.out, "\tvar imports %sImports\n", worldName)
	fmt.Fprintln(&r.out, "\tif len(_witgoImportSets) == 1 { imports = _witgoImportSets[0] }")
	fmt.Fprintln(&r.out, "\t_ = imports")
	r.renderHostImportList(imports, "imports")
	fmt.Fprintln(&r.out, "\t_witgoOpenRuntime := func(ctx context.Context) (runtimeCaller, error) {")
	fmt.Fprintf(&r.out, "\t\treturn witgo.LoadRuntimeWithContractContext(ctx, filename, _witgoOptions, _witgoImports, %sPing())\n", worldName)
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintln(&r.out, "\truntime, err := _witgoOpenRuntime(ctx)")
	fmt.Fprintln(&r.out, "\tif err != nil {")
	fmt.Fprintln(&r.out, "\t\treturn nil, err")
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintf(&r.out, "\treturn new%s(runtime, _witgoOpenRuntime)\n", worldName)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "func new%s(runtime runtimeCaller, reopen func(context.Context) (runtimeCaller, error)) (*%s, error) {\n", worldName, worldName)
	fmt.Fprintln(&r.out, "\tif runtime == nil {")
	fmt.Fprintln(&r.out, `		return nil, fmt.Errorf("runtime is nil")`)
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintf(&r.out, "\tclient := &%s{runtime: runtime, reopen: reopen", worldName)
	for _, export := range exports {
		fmt.Fprintf(&r.out, ", %sClient: &%s{runtime: runtime}", goLocalName(export.name), export.clientName(worldName))
	}
	fmt.Fprintln(&r.out, "}")
	for _, export := range exports {
		fmt.Fprintf(&r.out, "\tclient.%s = client.%sClient\n", goName(export.name), goLocalName(export.name))
	}
	fmt.Fprintln(&r.out, "\treturn client, nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	for _, export := range exports {
		fmt.Fprintf(&r.out, "var _ %s = (*%s)(nil)\n", export.interfaceName, export.clientName(worldName))
	}
	if len(exports) > 0 {
		fmt.Fprintln(&r.out)
	}
	for _, export := range exports {
		for _, fn := range export.functions {
			if err := r.renderClientMethod(export.clientName(worldName), export.callName, fn); err != nil {
				return err
			}
		}
	}
	for _, fn := range directFunctions {
		if err := r.renderClientMethod(worldName, "", fn); err != nil {
			return err
		}
	}
	return nil
}

func (r *renderer) renderHostImportList(imports []worldInterface, importsVariable string) {
	fmt.Fprintln(&r.out, "\tvar _witgoImports []witgo.HostImport")
	for _, imported := range imports {
		host := importsVariable + "." + goName(imported.name)
		fmt.Fprintf(&r.out, "\tif %s != nil {\n", host)
		fmt.Fprintf(&r.out, "\t\tif _witgoSource, ok := %s.(interface{ witgoCompositionPlug() (witgo.CompositionPlug, bool) }); ok {\n", host)
		fmt.Fprintln(&r.out, "\t\t\t_witgoPlug, available := _witgoSource.witgoCompositionPlug()")
		fmt.Fprintln(&r.out, "\t\t\tif !available { return nil, witgo.ErrPluginProviderClosed }")
		fmt.Fprintf(&r.out, "\t\t\tif _witgoPlug.Interface != %s { return nil, fmt.Errorf(\"%%w: expected interface %%q, provider exposes %%q\", witgo.ErrPluginDependencyMismatch, %s, _witgoPlug.Interface) }\n", strconv.Quote(imported.callName), strconv.Quote(imported.callName))
		fmt.Fprintln(&r.out, "\t\t\t_witgoOptions.CompositionPlugs = append(_witgoOptions.CompositionPlugs, _witgoPlug)")
		fmt.Fprintln(&r.out, "\t\t} else {")
		for _, fn := range imported.functions {
			fmt.Fprintln(&r.out, "\t\t_witgoImports = append(_witgoImports, witgo.HostImport{")
			fmt.Fprintf(&r.out, "\t\t\tInterface: %s, Function: %s,\n", strconv.Quote(imported.callName), strconv.Quote(fn.Name))
			fmt.Fprintln(&r.out, "\t\t\tCallContext: func(ctx context.Context, _witgoArgs []any) (any, error) {")
			fmt.Fprintf(&r.out, "\t\t\t\tif len(_witgoArgs) != %d { return nil, fmt.Errorf(%q, len(_witgoArgs)) }\n", len(fn.Params), "host import "+imported.callName+"#"+fn.Name+" received %d arguments")
			args := make([]string, 0, len(fn.Params))
			for index, param := range fn.Params {
				name := fmt.Sprintf("_witgoArg%d", index)
				fmt.Fprintf(&r.out, "\t\t\t\t%s, err := %s\n", name, r.liftRuntimeExpr("nil", fmt.Sprintf("_witgoArgs[%d]", index), param.Type))
				fmt.Fprintln(&r.out, "\t\t\t\tif err != nil { return nil, err }")
				args = append(args, name)
			}
			callArgs := append([]string{"ctx"}, args...)
			call := host + "." + goName(fn.Name) + "(" + strings.Join(callArgs, ", ") + ")"
			if _, _, mapped := r.resultErrorParts(fn); mapped {
				r.renderResultErrorProvider("\t\t\t\t", call, fn)
			} else if fn.Result == nil {
				fmt.Fprintf(&r.out, "\t\t\t\treturn nil, %s\n", call)
			} else if conversion, ok := r.conversionName(fn.Result); ok {
				fmt.Fprintf(&r.out, "\t\t\t\t_witgoResult, err := %s\n", call)
				fmt.Fprintln(&r.out, "\t\t\t\tif err != nil { return nil, err }")
				fmt.Fprintf(&r.out, "\t\t\t\treturn lower%s(_witgoResult), nil\n", conversion)
			} else {
				fmt.Fprintf(&r.out, "\t\t\t\treturn %s\n", call)
			}
			fmt.Fprintln(&r.out, "\t\t\t},")
			fmt.Fprintln(&r.out, "\t\t})")
		}
		fmt.Fprintln(&r.out, "\t\t}")
		fmt.Fprintln(&r.out, "\t}")
	}
}

func (r *renderer) renderResultErrorProvider(indent, call string, fn *ir.Func) {
	okType, errType, _ := r.resultErrorParts(fn)
	r.needsErrors = true
	if isUnitType(okType) {
		fmt.Fprintf(&r.out, "%s_witgoErr := %s\n", indent, call)
	} else {
		fmt.Fprintf(&r.out, "%s_witgoOK, _witgoErr := %s\n", indent, call)
	}
	fmt.Fprintf(&r.out, "%sif _witgoErr != nil {\n", indent)
	fmt.Fprintf(&r.out, "%s\tvar _witgoWITErr witgo.WITError[%s]\n", indent, r.goType(errType))
	fmt.Fprintf(&r.out, "%s\tif errors.As(_witgoErr, &_witgoWITErr) { return witgo.Err[%s](_witgoWITErr.Value), nil }\n", indent, r.goType(okType))
	fmt.Fprintf(&r.out, "%s\treturn nil, _witgoErr\n%s}\n", indent, indent)
	if isUnitType(okType) {
		fmt.Fprintf(&r.out, "%sreturn witgo.Ok[witgo.Unit, %s](witgo.UnitValue()), nil\n", indent, r.goType(errType))
	} else {
		fmt.Fprintf(&r.out, "%sreturn witgo.Ok[%s, %s](_witgoOK), nil\n", indent, r.goType(okType), r.goType(errType))
	}
}

func (r *renderer) renderFunctionNames(field string, names []string) {
	fmt.Fprintf(&r.out, "\t\t%s: []string{\n", field)
	for _, name := range names {
		fmt.Fprintf(&r.out, "\t\t\t%s,\n", strconv.Quote(name))
	}
	fmt.Fprintln(&r.out, "\t\t},")
}

func (r *renderer) renderFunctionSignatures(imports, exports map[string]string) {
	fmt.Fprintln(&r.out, "\t\tSignatures: map[string]string{")
	keys := make([]string, 0, len(imports)+len(exports))
	for name := range imports {
		keys = append(keys, name)
	}
	for name := range exports {
		keys = append(keys, name)
	}
	sort.Strings(keys)
	for _, name := range keys {
		signature := imports[name]
		if signature == "" {
			signature = exports[name]
		}
		fmt.Fprintf(&r.out, "\t\t\t%s: %s,\n", strconv.Quote(name), strconv.Quote(signature))
	}
	fmt.Fprintln(&r.out, "\t\t},")
}

func contractFunctionNames(interfaces []worldInterface, direct []*ir.Func) []string {
	var names []string
	for _, iface := range interfaces {
		for _, function := range iface.functions {
			name := function.Name
			if iface.callName != "" {
				name = iface.callName + "#" + name
			}
			names = append(names, name)
		}
	}
	for _, function := range direct {
		names = append(names, function.Name)
	}
	sort.Strings(names)
	return names
}

func contractFunctionSignatures(r *renderer, interfaces []worldInterface, direct []*ir.Func) map[string]string {
	result := make(map[string]string)
	for _, iface := range interfaces {
		for _, function := range iface.functions {
			name := function.Name
			if iface.callName != "" {
				name = iface.callName + "#" + name
			}
			result[name] = r.contractTypeSignature(function)
		}
	}
	for _, function := range direct {
		result[function.Name] = r.contractTypeSignature(function)
	}
	return result
}

func (r *renderer) contractTypeSignature(function *ir.Func) string {
	params := make([]string, 0, len(function.Params))
	for _, param := range function.Params {
		params = append(params, r.canonicalType(param.Type, nil))
	}
	results := []string{}
	if function.Result != nil {
		results = append(results, r.canonicalType(function.Result, nil))
	}
	return "(" + strings.Join(params, ",") + ")->(" + strings.Join(results, ",") + ")"
}

func (r *renderer) canonicalType(typ ir.Type, seen map[string]bool) string {
	if seen == nil {
		seen = make(map[string]bool)
	}
	switch typ := typ.(type) {
	case *ir.PrimitiveType:
		return typ.Name
	case *ir.NamedType:
		if typ.Name == "error-context" {
			return "error-context"
		}
		if seen[typ.Name] {
			return "recursive<" + typ.Name + ">"
		}
		decl := r.namedTypes[typ.Name]
		if decl == nil {
			return "named<" + typ.Name + ">"
		}
		next := make(map[string]bool, len(seen)+1)
		for name := range seen {
			next[name] = true
		}
		next[typ.Name] = true
		switch decl := decl.(type) {
		case *ir.TypeDef:
			return r.canonicalType(decl.Type, next)
		case *ir.Record:
			parts := make([]string, 0, len(decl.Fields))
			for _, field := range decl.Fields {
				parts = append(parts, field.Name+":"+r.canonicalType(field.Type, next))
			}
			return "record{" + strings.Join(parts, ",") + "}"
		case *ir.Enum:
			return "enum{" + strings.Join(decl.Cases, ",") + "}"
		case *ir.Flags:
			return "flags{" + strings.Join(decl.Flags, ",") + "}"
		case *ir.Variant:
			parts := make([]string, 0, len(decl.Cases))
			for _, item := range decl.Cases {
				part := item.Name
				if item.Type != nil {
					part += ":" + r.canonicalType(item.Type, next)
				}
				parts = append(parts, part)
			}
			return "variant{" + strings.Join(parts, ",") + "}"
		case *ir.Resource:
			return "own"
		}
	case *ir.GenericType:
		if typ.Name == "borrow" || typ.Name == "own" {
			return typ.Name
		}
		parts := make([]string, 0, len(typ.Args))
		for _, arg := range typ.Args {
			parts = append(parts, r.canonicalType(arg, seen))
		}
		return typ.Name + "<" + strings.Join(parts, ",") + ">"
	case *ir.TupleType:
		parts := make([]string, 0, len(typ.Items))
		for _, item := range typ.Items {
			parts = append(parts, r.canonicalType(item, seen))
		}
		return "tuple<" + strings.Join(parts, ",") + ">"
	}
	return fmt.Sprintf("unsupported<%T>", typ)
}

type worldInterface struct {
	name          string
	interfaceName string
	callName      string
	functions     []*ir.Func
}

func (w worldInterface) clientName(worldName string) string {
	return goLocalName(worldName + "-" + w.name + "-client")
}

func (r *renderer) worldParts(world *ir.World) ([]worldInterface, []worldInterface, []*ir.Func, error) {
	var imports []worldInterface
	var exports []worldInterface
	var direct []*ir.Func
	for _, item := range world.Items {
		switch item := item.(type) {
		case *ir.Import:
			resolved, err := r.resolveExtern(item.Name, item.Extern)
			if err != nil {
				return nil, nil, nil, fmt.Errorf("world %q import %q: %w", world.Name, item.Name, err)
			}
			imports = append(imports, resolved)
		case *ir.Export:
			resolved, err := r.resolveExtern(item.Name, item.Extern)
			if err != nil {
				return nil, nil, nil, fmt.Errorf("world %q export %q: %w", world.Name, item.Name, err)
			}
			exports = append(exports, resolved)
		case *ir.Func:
			direct = append(direct, item)
		case *ir.Use, *ir.Include, *ir.TypeDef, *ir.Record, *ir.Flags, *ir.Enum, *ir.Variant, *ir.Resource:
		default:
			return nil, nil, nil, fmt.Errorf("world %q: unsupported item %T", world.Name, item)
		}
	}
	return imports, exports, direct, nil
}

func (r *renderer) resolveExtern(name string, extern ir.ExternType) (worldInterface, error) {
	switch extern := extern.(type) {
	case *ir.ExternPath:
		if len(extern.Path.Segments) == 0 {
			return worldInterface{}, fmt.Errorf("empty interface path")
		}
		pathName := extern.Path.Segments[len(extern.Path.Segments)-1]
		iface, ok := r.interfaces[pathName]
		if !ok {
			return worldInterface{}, fmt.Errorf("interface %q was not found", pathName)
		}
		return worldInterface{
			name:          name,
			interfaceName: goName(pathName),
			callName:      r.interfaceID(pathName),
			functions:     interfaceFunctions(iface.Items),
		}, nil
	case *ir.InlineInterface:
		interfaceName := goName(name)
		if err := r.renderInterface(name, extern.Items); err != nil {
			return worldInterface{}, err
		}
		return worldInterface{
			name:          name,
			interfaceName: interfaceName,
			callName:      r.interfaceID(name),
			functions:     interfaceFunctions(extern.Items),
		}, nil
	case *ir.FuncType:
		interfaceName := goName(name)
		items := []ir.InterfaceItem{extern.Func}
		if err := r.renderInterface(name, items); err != nil {
			return worldInterface{}, err
		}
		return worldInterface{
			name:          name,
			interfaceName: interfaceName,
			callName:      "",
			functions:     []*ir.Func{extern.Func},
		}, nil
	default:
		return worldInterface{}, fmt.Errorf("unsupported extern type %T", extern)
	}
}

func interfaceFunctions(items []ir.InterfaceItem) []*ir.Func {
	var functions []*ir.Func
	for _, item := range items {
		if fn, ok := item.(*ir.Func); ok {
			functions = append(functions, fn)
		}
	}
	return functions
}

func (r *renderer) renderClientMethod(worldName, interfaceName string, fn *ir.Func) error {
	fmt.Fprintf(&r.out, "func (c *%s) %s%s {\n", worldName, goName(fn.Name), r.clientSignature(fn))
	args := make([]string, 0, len(fn.Params))
	for index, param := range fn.Params {
		name := paramName(param, index)
		args = append(args, r.lowerExpr(name, param.Type))
	}
	callName := fn.Name
	if interfaceName != "" {
		callName = interfaceName + "#" + fn.Name
	}
	if fn.Result == nil {
		fmt.Fprintf(&r.out, "\t_, _witgoErr := c.runtime.CallContext(ctx, %s", strconv.Quote(callName))
		for _, arg := range args {
			fmt.Fprintf(&r.out, ", %s", arg)
		}
		fmt.Fprintln(&r.out, ")")
		fmt.Fprintln(&r.out, "\treturn _witgoErr")
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
		return nil
	}

	fmt.Fprintf(&r.out, "\t_witgoValue, _witgoErr := c.runtime.CallContext(ctx, %s", strconv.Quote(callName))
	for _, arg := range args {
		fmt.Fprintf(&r.out, ", %s", arg)
	}
	fmt.Fprintln(&r.out, ")")
	if _, _, mapped := r.resultErrorParts(fn); mapped {
		r.renderResultErrorClient("\t", "_witgoValue", fn)
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
		return nil
	}
	fmt.Fprintf(&r.out, "\tif _witgoErr != nil {\n\t\treturn %s, _witgoErr\n\t}\n", r.zeroValue(fn.Result))
	fmt.Fprintf(&r.out, "\t_witgoResult, _witgoErr := %s\n", r.liftRuntimeExpr("c.runtime", "_witgoValue", fn.Result))
	fmt.Fprintf(&r.out, "\tif _witgoErr != nil {\n\t\treturn %s, fmt.Errorf(%q, _witgoErr)\n\t}\n", r.zeroValue(fn.Result), "call "+callName+": %w")
	if named, ok := fn.Result.(*ir.NamedType); ok && len(r.modelFuncs[named.Name]) > 0 {
		fmt.Fprintln(&r.out, "\t_witgoResult.binding = c")
	}
	fmt.Fprintln(&r.out, "\treturn _witgoResult, nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	return nil
}

func (r *renderer) renderResultErrorClient(indent, raw string, fn *ir.Func) {
	okType, errType, _ := r.resultErrorParts(fn)
	if isUnitType(okType) {
		fmt.Fprintf(&r.out, "%sif _witgoErr != nil { return _witgoErr }\n", indent)
	} else {
		fmt.Fprintf(&r.out, "%sif _witgoErr != nil { return %s, _witgoErr }\n", indent, r.zeroValue(okType))
	}
	fmt.Fprintf(&r.out, "%s_witgoResult, _witgoErr := liftValue[witgo.Result[%s, %s]](%s)\n", indent, r.goType(okType), r.goType(errType), raw)
	if isUnitType(okType) {
		fmt.Fprintf(&r.out, "%sif _witgoErr != nil { return _witgoErr }\n", indent)
		fmt.Fprintf(&r.out, "%sif value, failed := _witgoResult.GetErr(); failed { return witgo.NewWITError(value) }\n", indent)
		fmt.Fprintf(&r.out, "%sreturn nil\n", indent)
	} else {
		fmt.Fprintf(&r.out, "%sif _witgoErr != nil { return %s, _witgoErr }\n", indent, r.zeroValue(okType))
		fmt.Fprintf(&r.out, "%sif value, failed := _witgoResult.GetErr(); failed { return %s, witgo.NewWITError(value) }\n", indent, r.zeroValue(okType))
		fmt.Fprintf(&r.out, "%svalue, _ := _witgoResult.GetOK()\n%sreturn value, nil\n", indent, indent)
	}
}

func (r *renderer) contractSignature(fn *ir.Func) string {
	r.needsContext = true
	params := r.contextParams(fn.Params)
	if okType, _, mapped := r.resultErrorParts(fn); mapped {
		if isUnitType(okType) {
			return "(" + params + ") error"
		}
		return "(" + params + ") (" + r.goType(okType) + ", error)"
	}
	if fn.Result == nil {
		return "(" + params + ")"
	}
	return "(" + params + ") " + r.goType(fn.Result)
}

func (r *renderer) clientSignature(fn *ir.Func) string {
	r.needsContext = true
	params := r.contextParams(fn.Params)
	if okType, _, mapped := r.resultErrorParts(fn); mapped {
		if isUnitType(okType) {
			return "(" + params + ") error"
		}
		return "(" + params + ") (" + r.goType(okType) + ", error)"
	}
	if fn.Result == nil {
		return "(" + params + ") error"
	}
	return "(" + params + ") (" + r.goType(fn.Result) + ", error)"
}

func (r *renderer) modelSignature(fn *ir.Func) string {
	r.needsContext = true
	params := r.contextParams(fn.Params[1:])
	if okType, _, mapped := r.resultErrorParts(fn); mapped {
		if isUnitType(okType) {
			return "(" + params + ") error"
		}
		return "(" + params + ") (" + r.goType(okType) + ", error)"
	}
	if fn.Result == nil {
		return "(" + params + ") error"
	}
	return "(" + params + ") (" + r.goType(fn.Result) + ", error)"
}

func (r *renderer) resultErrorParts(fn *ir.Func) (ir.Type, ir.Type, bool) {
	if r.goOverlay == nil {
		return nil, nil, false
	}
	found := false
	for _, mapping := range r.goOverlay.errors {
		if mapping.Function == fn {
			found = true
			break
		}
	}
	if !found {
		return nil, nil, false
	}
	result, ok := fn.Result.(*ir.GenericType)
	if !ok || result.Name != "result" {
		return nil, nil, false
	}
	okType := ir.Type(&ir.NamedType{Wildcard: true})
	errType := ir.Type(&ir.NamedType{Wildcard: true})
	if len(result.Args) > 0 {
		okType = result.Args[0]
	}
	if len(result.Args) > 1 {
		errType = result.Args[1]
	}
	return okType, errType, true
}

func isUnitType(typ ir.Type) bool {
	named, ok := typ.(*ir.NamedType)
	return ok && named.Wildcard
}

func (r *renderer) contextParams(params []ir.Param) string {
	rest := r.params(params)
	if rest == "" {
		return "ctx context.Context"
	}
	return "ctx context.Context, " + rest
}

func (r *renderer) params(params []ir.Param) string {
	out := make([]string, 0, len(params))
	for index, param := range params {
		out = append(out, paramName(param, index)+" "+r.goType(param.Type))
	}
	return strings.Join(out, ", ")
}

func paramName(param ir.Param, index int) string {
	if param.Name == "" || param.Name == "self" {
		return fmt.Sprintf("arg%d", index)
	}
	return goLocalName(param.Name)
}

func modelMethodName(recordName, functionName string) string {
	method := goName(functionName)
	record := goName(recordName)
	if strings.HasSuffix(method, record) && len(method) > len(record) {
		return strings.TrimSuffix(method, record)
	}
	return method
}

func (r *renderer) goType(typ ir.Type) string {
	switch typ := typ.(type) {
	case nil:
		return "any"
	case *ir.PrimitiveType:
		if mapped, ok := primitiveType(typ.Name); ok {
			if typ.Name == "char" {
				r.needsWitgo = true
			}
			return mapped
		}
		return "any"
	case *ir.NamedType:
		if typ.Wildcard {
			r.needsWitgo = true
			return "witgo.Unit"
		}
		if typ.Name == "error-context" {
			return "witgo.Handle"
		}
		if mapped, ok := primitiveType(typ.Name); ok {
			if typ.Name == "char" {
				r.needsWitgo = true
			}
			return mapped
		}
		return goName(typ.Name)
	case *ir.GenericType:
		switch typ.Name {
		case "list":
			return "[]" + r.goType(firstType(typ.Args))
		case "option":
			r.needsWitgo = true
			return "witgo.Option[" + r.goType(firstType(typ.Args)) + "]"
		case "borrow", "own", "future", "stream":
			return "witgo.Handle"
		case "map":
			if len(typ.Args) == 2 {
				r.needsWitgo = true
				return "witgo.Map[" + r.goType(typ.Args[0]) + ", " + r.goType(typ.Args[1]) + "]"
			}
		case "result":
			r.needsWitgo = true
			if len(typ.Args) == 2 {
				return "witgo.Result[" + r.goType(typ.Args[0]) + ", " + r.goType(typ.Args[1]) + "]"
			}
			if len(typ.Args) == 1 {
				return "witgo.Result[" + r.goType(typ.Args[0]) + ", witgo.Unit]"
			}
			return "witgo.Result[witgo.Unit, witgo.Unit]"
		}
		args := make([]string, 0, len(typ.Args))
		for _, arg := range typ.Args {
			args = append(args, r.goType(arg))
		}
		return goName(typ.Name) + "[" + strings.Join(args, ", ") + "]"
	case *ir.TupleType:
		r.needsWitgo = true
		if len(typ.Items) > 16 {
			return "witgo.Tuple"
		}
		if len(typ.Items) == 0 {
			return "witgo.Tuple0"
		}
		args := make([]string, 0, len(typ.Items))
		for _, item := range typ.Items {
			args = append(args, r.goType(item))
		}
		return fmt.Sprintf("witgo.Tuple%d[%s]", len(args), strings.Join(args, ", "))
	default:
		return "any"
	}
}

func (r *renderer) typeMapping(name string) (resolvedTypeMapping, bool) {
	if r.goOverlay == nil {
		return resolvedTypeMapping{}, false
	}
	mapping, ok := r.goOverlay.types[name]
	return mapping, ok
}

func (r *renderer) recordHasOverlay(record *ir.Record) bool {
	for _, field := range record.Fields {
		if r.typeHasOverlay(field.Type, make(map[string]bool)) {
			return true
		}
	}
	return false
}

func (r *renderer) typeHasOverlay(typ ir.Type, seen map[string]bool) bool {
	switch typ := typ.(type) {
	case *ir.NamedType:
		if _, ok := r.typeMapping(typ.Name); ok {
			return true
		}
		if seen[typ.Name] {
			return false
		}
		seen[typ.Name] = true
		switch decl := r.namedTypes[typ.Name].(type) {
		case *ir.TypeDef:
			return r.typeHasOverlay(decl.Type, seen)
		case *ir.Record:
			return r.recordHasOverlay(decl)
		}
	case *ir.GenericType:
		for _, arg := range typ.Args {
			if r.typeHasOverlay(arg, seen) {
				return true
			}
		}
	case *ir.TupleType:
		for _, item := range typ.Items {
			if r.typeHasOverlay(item, seen) {
				return true
			}
		}
	}
	return false
}

func (r *renderer) wireGoType(typ ir.Type) string {
	switch typ := typ.(type) {
	case *ir.NamedType:
		if mapping, ok := r.typeMapping(typ.Name); ok {
			return r.wireGoType(mapping.Wire)
		}
		if record, ok := r.namedTypes[typ.Name].(*ir.Record); ok && r.recordHasOverlay(record) {
			return goLocalName(typ.Name) + "Wire"
		}
		return r.goType(typ)
	case *ir.GenericType, *ir.TupleType:
		return r.goType(typ)
	default:
		return r.goType(typ)
	}
}

func (r *renderer) renderMappedAliasCodec(decl *ir.TypeDef, mapping resolvedTypeMapping) {
	name := goName(decl.Name)
	wire := r.wireGoType(decl.Type)
	fmt.Fprintf(&r.out, "func lower%s(value %s) %s {\n", name, mapping.Config.GoType, wire)
	switch mapping.Config.Codec {
	case "unix-seconds":
		fmt.Fprintln(&r.out, "\treturn value.Unix()")
	case "unix-milliseconds":
		fmt.Fprintln(&r.out, "\treturn value.UnixMilli()")
	case "unix-nanoseconds":
		fmt.Fprintln(&r.out, "\treturn value.UnixNano()")
	case "duration-nanoseconds":
		fmt.Fprintf(&r.out, "\treturn %s(value)\n", wire)
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintf(&r.out, "func lift%s(value %s) %s {\n", name, wire, mapping.Config.GoType)
	switch mapping.Config.Codec {
	case "unix-seconds":
		fmt.Fprintln(&r.out, "\treturn time.Unix(value, 0)")
	case "unix-milliseconds":
		fmt.Fprintln(&r.out, "\treturn time.UnixMilli(value)")
	case "unix-nanoseconds":
		fmt.Fprintln(&r.out, "\treturn time.Unix(0, value)")
	case "duration-nanoseconds":
		fmt.Fprintln(&r.out, "\treturn time.Duration(value)")
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintf(&r.out, "func liftRuntime%s(value any) (%s, error) {\n", name, mapping.Config.GoType)
	fmt.Fprintf(&r.out, "\twire, err := liftValue[%s](value)\n", wire)
	fmt.Fprintln(&r.out, "\tif err != nil { var zero "+mapping.Config.GoType+"; return zero, err }")
	fmt.Fprintf(&r.out, "\treturn lift%s(wire), nil\n", name)
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
}

func (r *renderer) conversionName(typ ir.Type) (string, bool) {
	named, ok := typ.(*ir.NamedType)
	if !ok {
		return "", false
	}
	if _, ok := r.typeMapping(named.Name); ok {
		return goName(named.Name), true
	}
	if record, ok := r.namedTypes[named.Name].(*ir.Record); ok && r.recordHasOverlay(record) {
		return goName(named.Name), true
	}
	return "", false
}

func (r *renderer) renderRecordCodec(record *ir.Record) {
	publicName := goName(record.Name)
	wireName := goLocalName(record.Name) + "Wire"
	fmt.Fprintf(&r.out, "type %s struct {\n", wireName)
	for _, field := range record.Fields {
		fmt.Fprintf(&r.out, "\t%s %s `json:%s`\n", goName(field.Name), r.wireGoType(field.Type), strconv.Quote(field.Name))
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintf(&r.out, "func lower%s(value %s) %s {\n", publicName, publicName, wireName)
	fmt.Fprintf(&r.out, "\tvar wire %s\n", wireName)
	for _, field := range record.Fields {
		fieldName := goName(field.Name)
		if conversion, ok := r.conversionName(field.Type); ok {
			fmt.Fprintf(&r.out, "\twire.%s = lower%s(value.%s)\n", fieldName, conversion, fieldName)
		} else {
			fmt.Fprintf(&r.out, "\twire.%s = value.%s\n", fieldName, fieldName)
		}
	}
	fmt.Fprintln(&r.out, "\treturn wire\n}")
	fmt.Fprintf(&r.out, "func lift%s(wire %s) %s {\n", publicName, wireName, publicName)
	fmt.Fprintf(&r.out, "\tvar value %s\n", publicName)
	for _, field := range record.Fields {
		fieldName := goName(field.Name)
		if conversion, ok := r.conversionName(field.Type); ok {
			fmt.Fprintf(&r.out, "\tvalue.%s = lift%s(wire.%s)\n", fieldName, conversion, fieldName)
		} else {
			fmt.Fprintf(&r.out, "\tvalue.%s = wire.%s\n", fieldName, fieldName)
		}
	}
	fmt.Fprintln(&r.out, "\treturn value\n}")
	fmt.Fprintf(&r.out, "func liftRuntime%s(raw any) (%s, error) {\n", publicName, publicName)
	fmt.Fprintf(&r.out, "\twire, err := liftValue[%s](raw)\n", wireName)
	fmt.Fprintf(&r.out, "\tif err != nil { var zero %s; return zero, err }\n", publicName)
	fmt.Fprintf(&r.out, "\treturn lift%s(wire), nil\n}\n\n", publicName)
}

func (r *renderer) lowerExpr(expression string, typ ir.Type) string {
	if conversion, ok := r.conversionName(typ); ok {
		return "lower" + conversion + "(" + expression + ")"
	}
	return expression
}

func (r *renderer) liftExpr(expression string, typ ir.Type) string {
	return "liftValue[" + r.goType(typ) + "](" + expression + ")"
}

func (r *renderer) liftRuntimeExpr(runtime, expression string, typ ir.Type) string {
	if conversion, ok := r.conversionName(typ); ok {
		return "liftRuntime" + conversion + "(" + expression + ")"
	}
	return r.liftExpr(expression, typ)
}

func (r *renderer) zeroValue(typ ir.Type) string {
	return "*new(" + r.goType(typ) + ")"
}

func primitiveType(name string) (string, bool) {
	types := map[string]string{
		"bool": "bool", "char": "witgo.Char", "string": "string",
		"u8": "uint8", "u16": "uint16", "u32": "uint32", "u64": "uint64",
		"s8": "int8", "s16": "int16", "s32": "int32", "s64": "int64",
		"f32": "float32", "f64": "float64",
	}
	result, ok := types[name]
	return result, ok
}

func (r *renderer) interfaceID(name string) string {
	if r.witPackage == nil {
		return name
	}
	id := r.witPackage.Namespace + ":" + r.witPackage.Name + "/" + name
	if r.witPackage.Version != "" {
		id += "@" + r.witPackage.Version
	}
	return id
}

func witPackageID(witPackage *ir.Package) string {
	if witPackage == nil {
		return ""
	}
	id := witPackage.Namespace + ":" + witPackage.Name
	if witPackage.Version != "" {
		id += "@" + witPackage.Version
	}
	return id
}

func goPackageName(name string) string {
	var out strings.Builder
	for _, char := range strings.ToLower(name) {
		if unicode.IsLetter(char) || unicode.IsDigit(char) || char == '_' {
			out.WriteRune(char)
		} else {
			out.WriteRune('_')
		}
	}
	result := strings.Trim(out.String(), "_")
	if result == "" || unicode.IsDigit([]rune(result)[0]) || goKeywords[result] {
		return "wit_" + result
	}
	return result
}

func firstType(types []ir.Type) ir.Type {
	if len(types) == 0 {
		return nil
	}
	return types[0]
}

func isPackageName(name string) bool {
	if name == "" {
		return false
	}
	for index, char := range name {
		if index == 0 && !unicode.IsLetter(char) && char != '_' {
			return false
		}
		if index > 0 && !unicode.IsLetter(char) && !unicode.IsDigit(char) && char != '_' {
			return false
		}
	}
	return !goKeywords[name]
}

func goName(name string) string {
	words := strings.FieldsFunc(name, func(char rune) bool {
		return char == '-' || char == '_' || unicode.IsSpace(char)
	})
	for index, word := range words {
		lower := strings.ToLower(word)
		if initialisms[lower] {
			words[index] = strings.ToUpper(lower)
			continue
		}
		runes := []rune(word)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		words[index] = string(runes)
	}
	result := strings.Join(words, "")
	if result == "" {
		return "Value"
	}
	if unicode.IsDigit([]rune(result)[0]) {
		result = "Value" + result
	}
	return result
}

func goLocalName(name string) string {
	exported := goName(name)
	if initialisms[strings.ToLower(exported)] {
		return strings.ToLower(exported)
	}
	runes := []rune(exported)
	runes[0] = unicode.ToLower(runes[0])
	result := string(runes)
	if goKeywords[result] {
		return result + "Value"
	}
	return result
}

var initialisms = map[string]bool{
	"api": true, "http": true, "https": true, "id": true, "ip": true,
	"json": true, "sql": true, "sso": true, "tcp": true, "udp": true,
	"uri": true, "url": true, "uuid": true, "xml": true,
}

var goKeywords = map[string]bool{
	"break": true, "default": true, "func": true, "interface": true,
	"select": true, "case": true, "defer": true, "go": true, "map": true,
	"struct": true, "chan": true, "else": true, "goto": true, "package": true,
	"switch": true, "const": true, "fallthrough": true, "if": true,
	"range": true, "type": true, "continue": true, "for": true,
	"import": true, "return": true, "var": true,
}
