package generator

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"unicode"

	"github.com/slavkiy/witgo/parser/ir"
)

type renderer struct {
	out        bytes.Buffer
	interfaces map[string]*ir.Interface
	records    map[string]*ir.Record
	modelFuncs map[string][]*ir.Func
	exports    map[string]bool
	emitted    map[string]string
	needsFmt   bool
	hasResult  bool
	hasWorld   bool
	witPackage *ir.Package
}

// Render converts a lowered WIT file into unformatted Go source.
func Render(file *ir.File, packageName string) ([]byte, error) {
	if file == nil {
		return nil, fmt.Errorf("IR file is nil")
	}
	if !isPackageName(packageName) {
		return nil, fmt.Errorf("invalid Go package name %q", packageName)
	}

	r := &renderer{
		interfaces: make(map[string]*ir.Interface),
		records:    make(map[string]*ir.Record),
		modelFuncs: make(map[string][]*ir.Func),
		exports:    make(map[string]bool),
		emitted:    make(map[string]string),
		witPackage: file.Package,
	}
	r.collect(file)

	var body bytes.Buffer
	r.out = body
	if err := r.renderFile(file); err != nil {
		return nil, err
	}
	body = r.out

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by witgo. DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "package %s\n", packageName)
	if r.needsFmt || r.hasWorld {
		fmt.Fprintln(&out)
		fmt.Fprintln(&out, "import (")
		if r.hasWorld {
			fmt.Fprintln(&out, `	"encoding/json"`)
		}
		if r.needsFmt || r.hasWorld {
			fmt.Fprintln(&out, `	"fmt"`)
		}
		if r.hasWorld {
			fmt.Fprintln(&out, `	"github.com/slavkiy/witgo"`)
		}
		fmt.Fprintln(&out, ")")
	}
	fmt.Fprintln(&out)
	if file.Package != nil {
		fmt.Fprintln(&out, "const (")
		fmt.Fprintf(&out, "\tWITPackageNamespace = %s\n", strconv.Quote(file.Package.Namespace))
		fmt.Fprintf(&out, "\tWITPackageName = %s\n", strconv.Quote(file.Package.Name))
		fmt.Fprintf(&out, "\tWITPackageVersion = %s\n", strconv.Quote(file.Package.Version))
		fmt.Fprintf(&out, "\tWITPackageID = %s\n", strconv.Quote(witPackageID(file.Package)))
		fmt.Fprintln(&out, ")")
		fmt.Fprintln(&out)
	}
	if r.hasResult {
		fmt.Fprintln(&out, "type Result[OK, Err any] struct {")
		fmt.Fprintln(&out, "\tOK  *OK")
		fmt.Fprintln(&out, "\tErr *Err")
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
	}
	if r.needsFmt {
		fmt.Fprintln(&out, "func liftValue[T any](value any) (T, error) {")
		fmt.Fprintln(&out, "\tif typed, ok := value.(T); ok {")
		fmt.Fprintln(&out, "\t\treturn typed, nil")
		fmt.Fprintln(&out, "\t}")
		fmt.Fprintln(&out, "\tdata, err := json.Marshal(value)")
		fmt.Fprintln(&out, "\tif err != nil { var zero T; return zero, fmt.Errorf(\"encode component value: %w\", err) }")
		fmt.Fprintln(&out, "\tvar result T")
		fmt.Fprintln(&out, "\tif err := json.Unmarshal(data, &result); err != nil {")
		fmt.Fprintln(&out, "\t\treturn result, fmt.Errorf(\"decode component value: %w\", err)")
		fmt.Fprintln(&out, "\t}")
		fmt.Fprintln(&out, "\treturn result, nil")
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
	}
	out.Write(body.Bytes())
	return out.Bytes(), nil
}

func (r *renderer) collect(file *ir.File) {
	for _, decl := range file.Decls {
		switch decl := decl.(type) {
		case *ir.Interface:
			r.interfaces[decl.Name] = decl
			for _, item := range decl.Items {
				if record, ok := item.(*ir.Record); ok {
					r.records[record.Name] = record
				}
				r.inspectItem(item)
			}
		case *ir.Record:
			r.records[decl.Name] = decl
		case *ir.World:
			r.needsFmt = true
			r.hasWorld = true
			for _, item := range decl.Items {
				r.inspectWorldItem(item)
				if export, ok := item.(*ir.Export); ok {
					if path, ok := export.Extern.(*ir.ExternPath); ok && len(path.Path.Segments) > 0 {
						r.exports[path.Path.Segments[len(path.Path.Segments)-1]] = true
					}
				}
			}
		case *ir.TypeDef:
			r.inspectType(decl.Type)
		}
	}
	for name, iface := range r.interfaces {
		if !r.exports[name] {
			continue
		}
		for _, fn := range interfaceFunctions(iface.Items) {
			if len(fn.Params) == 0 {
				continue
			}
			named, ok := fn.Params[0].Type.(*ir.NamedType)
			if ok && r.records[named.Name] != nil {
				r.modelFuncs[named.Name] = append(r.modelFuncs[named.Name], fn)
				r.needsFmt = true
			}
		}
	}
}

func (r *renderer) inspectItem(item ir.InterfaceItem) {
	switch item := item.(type) {
	case *ir.TypeDef:
		r.inspectType(item.Type)
	case *ir.Record:
		for _, field := range item.Fields {
			r.inspectType(field.Type)
		}
	case *ir.Variant:
		for _, variantCase := range item.Cases {
			r.inspectType(variantCase.Type)
		}
	case *ir.Func:
		for _, param := range item.Params {
			r.inspectType(param.Type)
		}
		r.inspectType(item.Result)
	}
}

func (r *renderer) inspectWorldItem(item ir.WorldItem) {
	switch item := item.(type) {
	case *ir.Func:
		r.inspectType(item.Result)
	case *ir.Import:
		r.inspectExtern(item.Extern)
	case *ir.Export:
		r.inspectExtern(item.Extern)
	}
}

func (r *renderer) inspectExtern(extern ir.ExternType) {
	switch extern := extern.(type) {
	case *ir.InlineInterface:
		for _, item := range extern.Items {
			r.inspectItem(item)
		}
	case *ir.FuncType:
		r.inspectType(extern.Func.Result)
	}
}

func (r *renderer) inspectType(typ ir.Type) {
	switch typ := typ.(type) {
	case *ir.GenericType:
		if typ.Name == "result" {
			r.hasResult = true
		}
		for _, arg := range typ.Args {
			r.inspectType(arg)
		}
	case *ir.TupleType:
		for _, item := range typ.Items {
			r.inspectType(item)
		}
	}
}

func (r *renderer) renderFile(file *ir.File) error {
	for _, decl := range file.Decls {
		switch decl := decl.(type) {
		case *ir.Interface:
			if err := r.renderInterfaceTypes(decl); err != nil {
				return err
			}
		case *ir.World:
			if err := r.renderWorldTypes(decl); err != nil {
				return err
			}
		default:
			if err := r.renderTypeDecl(decl); err != nil {
				return err
			}
		}
	}

	for _, decl := range file.Decls {
		if iface, ok := decl.(*ir.Interface); ok {
			if err := r.renderInterface(iface.Name, iface.Items); err != nil {
				return err
			}
		}
	}

	worldCount := 0
	for _, decl := range file.Decls {
		if _, ok := decl.(*ir.World); ok {
			worldCount++
		}
	}
	if worldCount > 0 {
		fmt.Fprintln(&r.out, "type runtimeCaller interface {")
		fmt.Fprintln(&r.out, "\tCall(name string, args ...any) (any, error)")
		fmt.Fprintln(&r.out, "\tClose() error")
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
	}
	for _, decl := range file.Decls {
		if world, ok := decl.(*ir.World); ok {
			if err := r.renderWorld(world); err != nil {
				return err
			}
		}
	}
	return nil
}

func (r *renderer) renderInterfaceTypes(iface *ir.Interface) error {
	for _, item := range iface.Items {
		if _, ok := item.(*ir.Use); ok {
			continue
		}
		if _, ok := item.(*ir.Func); ok {
			continue
		}
		if err := r.renderTypeDecl(item); err != nil {
			return fmt.Errorf("interface %q: %w", iface.Name, err)
		}
	}
	return nil
}

func (r *renderer) renderWorldTypes(world *ir.World) error {
	for _, item := range world.Items {
		switch item := item.(type) {
		case *ir.Use, *ir.Func, *ir.Import, *ir.Export, *ir.Include:
			continue
		default:
			if err := r.renderTypeDecl(item); err != nil {
				return fmt.Errorf("world %q: %w", world.Name, err)
			}
		}
	}
	return nil
}

func (r *renderer) renderTypeDecl(decl any) error {
	switch decl := decl.(type) {
	case *ir.TypeDef:
		if !r.markEmitted(decl.Name, "type") {
			return nil
		}
		fmt.Fprintf(&r.out, "type %s = %s\n\n", goName(decl.Name), r.goType(decl.Type))
	case *ir.Record:
		if !r.markEmitted(decl.Name, "record") {
			return nil
		}
		r.renderRecord(decl)
	case *ir.Flags:
		if !r.markEmitted(decl.Name, "flags") {
			return nil
		}
		r.renderFlags(decl)
	case *ir.Enum:
		if !r.markEmitted(decl.Name, "enum") {
			return nil
		}
		r.renderEnum(decl)
	case *ir.Variant:
		if !r.markEmitted(decl.Name, "variant") {
			return nil
		}
		r.renderVariant(decl)
	case *ir.Resource:
		if !r.markEmitted(decl.Name, "resource") {
			return nil
		}
		r.renderResource(decl)
	case *ir.Interface, *ir.World:
		return nil
	default:
		return fmt.Errorf("unsupported declaration %T", decl)
	}
	return nil
}

func (r *renderer) markEmitted(name, kind string) bool {
	goIdentifier := goName(name)
	if _, exists := r.emitted[goIdentifier]; exists {
		return false
	}
	r.emitted[goIdentifier] = kind
	return true
}

func (r *renderer) renderRecord(record *ir.Record) {
	name := goName(record.Name)
	fmt.Fprintf(&r.out, "type %s struct {\n", name)
	for _, field := range record.Fields {
		fmt.Fprintf(&r.out, "\t%s %s `json:%s`\n", goName(field.Name), r.goType(field.Type), strconv.Quote(field.Name))
	}
	if len(r.modelFuncs[record.Name]) > 0 {
		fmt.Fprintf(&r.out, "\tbinding %sBinding\n", goLocalName(record.Name))
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	if functions := r.modelFuncs[record.Name]; len(functions) > 0 {
		fmt.Fprintf(&r.out, "type %sBinding interface {\n", goLocalName(record.Name))
		for _, fn := range functions {
			fmt.Fprintf(&r.out, "\t%s%s\n", goName(fn.Name), r.clientSignature(fn))
		}
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
		for _, fn := range functions {
			fmt.Fprintf(&r.out, "func (value %s) %s%s {\n", name, modelMethodName(record.Name, fn.Name), r.modelSignature(fn))
			fmt.Fprintln(&r.out, "\tif value.binding == nil {")
			if fn.Result == nil {
				fmt.Fprintln(&r.out, `		return fmt.Errorf("model is not attached to a plugin")`)
			} else {
				fmt.Fprintf(&r.out, "\t\treturn %s, fmt.Errorf(%q)\n", r.zeroValue(fn.Result), "model is not attached to a plugin")
			}
			fmt.Fprintln(&r.out, "\t}")
			args := []string{"value"}
			for index, param := range fn.Params[1:] {
				args = append(args, paramName(param, index+1))
			}
			fmt.Fprintf(&r.out, "\treturn value.binding.%s(%s)\n", goName(fn.Name), strings.Join(args, ", "))
			fmt.Fprintln(&r.out, "}")
			fmt.Fprintln(&r.out)
		}
	}

}

func (r *renderer) renderFlags(flags *ir.Flags) {
	name := goName(flags.Name)
	fmt.Fprintf(&r.out, "type %s uint64\n\n", name)
	fmt.Fprintln(&r.out, "const (")
	for index, flag := range flags.Flags {
		fmt.Fprintf(&r.out, "\t%s%s %s = 1 << %d\n", name, goName(flag), name, index)
	}
	fmt.Fprintln(&r.out, ")")
	fmt.Fprintln(&r.out)
}

func (r *renderer) renderEnum(enum *ir.Enum) {
	name := goName(enum.Name)
	fmt.Fprintf(&r.out, "type %s uint32\n\n", name)
	fmt.Fprintln(&r.out, "const (")
	for index, enumCase := range enum.Cases {
		fmt.Fprintf(&r.out, "\t%s%s %s = %d\n", name, goName(enumCase), name, index)
	}
	fmt.Fprintln(&r.out, ")")
	fmt.Fprintln(&r.out)
}

func (r *renderer) renderVariant(variant *ir.Variant) {
	name := goName(variant.Name)
	fmt.Fprintf(&r.out, "type %sKind uint32\n\n", name)
	fmt.Fprintln(&r.out, "const (")
	for index, variantCase := range variant.Cases {
		fmt.Fprintf(&r.out, "\t%sKind%s %sKind = %d\n", name, goName(variantCase.Name), name, index)
	}
	fmt.Fprintln(&r.out, ")")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "type %s struct {\n\tKind %sKind\n", name, name)
	for _, variantCase := range variant.Cases {
		if variantCase.Type != nil {
			fmt.Fprintf(&r.out, "\t%s *%s\n", goName(variantCase.Name), r.goType(variantCase.Type))
		}
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
}

func (r *renderer) renderResource(resource *ir.Resource) {
	fmt.Fprintf(&r.out, "type %s interface {\n", goName(resource.Name))
	for _, item := range resource.Items {
		fn, ok := item.(*ir.Func)
		if !ok || fn.Static {
			continue
		}
		fmt.Fprintf(&r.out, "\t%s%s\n", goName(fn.Name), r.contractSignature(fn))
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
}

func (r *renderer) renderInterface(name string, items []ir.InterfaceItem) error {
	var functions []*ir.Func
	for _, item := range items {
		if fn, ok := item.(*ir.Func); ok {
			functions = append(functions, fn)
		}
	}
	if len(functions) == 0 {
		return nil
	}
	if !r.markEmitted(name, "interface") {
		return nil
	}
	fmt.Fprintf(&r.out, "type %s interface {\n", goName(name))
	for _, fn := range functions {
		signature := r.contractSignature(fn)
		if r.exports[name] {
			signature = r.clientSignature(fn)
		}
		fmt.Fprintf(&r.out, "\t%s%s\n", goName(fn.Name), signature)
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	return nil
}

func (r *renderer) renderWorld(world *ir.World) error {
	imports, exports, directFunctions, err := r.worldParts(world)
	if err != nil {
		return err
	}
	worldName := goName(world.Name)

	fmt.Fprintf(&r.out, "type %s struct {\n", worldName)
	fmt.Fprintln(&r.out, "\truntime runtimeCaller")
	for _, imported := range imports {
		fmt.Fprintf(&r.out, "\t%s %s\n", goLocalName(imported.name), imported.interfaceName)
	}
	for _, export := range exports {
		fmt.Fprintf(&r.out, "\t%s %s\n", goName(export.name), export.interfaceName)
	}
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	fmt.Fprintf(&r.out, "func (c *%s) Close() error {\n", worldName)
	fmt.Fprintln(&r.out, "\tif c == nil || c.runtime == nil { return nil }")
	fmt.Fprintln(&r.out, "\treturn c.runtime.Close()")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	for _, export := range exports {
		fmt.Fprintf(&r.out, "type %s struct {\n", export.clientName(worldName))
		fmt.Fprintln(&r.out, "\truntime runtimeCaller")
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
	}

	fmt.Fprintf(&r.out, "func Open%s(filename string%s) (*%s, error) {\n", worldName, r.importParams(imports), worldName)
	fmt.Fprintf(&r.out, "\treturn Open%sWithOptions(filename, witgo.RuntimeOptions{}%s)\n", worldName, r.importArgs(imports))
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "func Open%sWithOptions(filename string, _witgoOptions witgo.RuntimeOptions%s) (*%s, error) {\n", worldName, r.importParams(imports), worldName)
	for _, imported := range imports {
		field := goLocalName(imported.name)
		fmt.Fprintf(&r.out, "\tif %s == nil {\n", field)
		fmt.Fprintf(&r.out, "\t\treturn nil, fmt.Errorf(%q)\n", world.Name+" import "+imported.name+" is nil")
		fmt.Fprintln(&r.out, "\t}")
	}
	r.renderHostImportList(imports)
	fmt.Fprintln(&r.out, "\truntime, err := witgo.LoadRuntimeWithImports(filename, _witgoOptions, _witgoImports)")
	fmt.Fprintln(&r.out, "\tif err != nil {")
	fmt.Fprintln(&r.out, "\t\treturn nil, err")
	fmt.Fprintln(&r.out, "\t}")
	fmt.Fprintf(&r.out, "\treturn new%s(runtime%s)\n", worldName, r.importArgs(imports))
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	fmt.Fprintf(&r.out, "func new%s(runtime runtimeCaller%s) (*%s, error) {\n", worldName, r.importParams(imports), worldName)
	fmt.Fprintln(&r.out, "\tif runtime == nil {")
	fmt.Fprintln(&r.out, `		return nil, fmt.Errorf("runtime is nil")`)
	fmt.Fprintln(&r.out, "\t}")
	for _, imported := range imports {
		field := goLocalName(imported.name)
		fmt.Fprintf(&r.out, "\tif %s == nil {\n", field)
		fmt.Fprintf(&r.out, "\t\treturn nil, fmt.Errorf(%q)\n", world.Name+" import "+imported.name+" is nil")
		fmt.Fprintln(&r.out, "\t}")
	}
	fmt.Fprintf(&r.out, "\treturn &%s{runtime: runtime", worldName)
	for _, imported := range imports {
		field := goLocalName(imported.name)
		fmt.Fprintf(&r.out, ", %s: %s", field, field)
	}
	for _, export := range exports {
		fmt.Fprintf(&r.out, ", %s: &%s{runtime: runtime}", goName(export.name), export.clientName(worldName))
	}
	fmt.Fprintln(&r.out, "}, nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)

	for _, export := range exports {
		fmt.Fprintf(&r.out, "var _ %s = (*%s)(nil)\n", export.interfaceName, export.clientName(worldName))
	}
	if len(exports) > 0 {
		fmt.Fprintln(&r.out)
	}
	for _, export := range exports {
		for _, fn := range export.functions {
			if err := r.renderClientMethod(export.clientName(worldName), export.callName, fn); err != nil {
				return err
			}
		}
	}
	for _, fn := range directFunctions {
		if err := r.renderClientMethod(worldName, "", fn); err != nil {
			return err
		}
	}
	return nil
}

func (r *renderer) renderHostImportList(imports []worldInterface) {
	fmt.Fprintln(&r.out, "\t_witgoImports := []witgo.HostImport{")
	for _, imported := range imports {
		host := goLocalName(imported.name)
		for _, fn := range imported.functions {
			fmt.Fprintln(&r.out, "\t\t{")
			fmt.Fprintf(&r.out, "\t\t\tInterface: %s, Function: %s,\n", strconv.Quote(imported.callName), strconv.Quote(fn.Name))
			fmt.Fprintln(&r.out, "\t\t\tCall: func(_witgoArgs []any) (any, error) {")
			fmt.Fprintf(&r.out, "\t\t\t\tif len(_witgoArgs) != %d { return nil, fmt.Errorf(%q, len(_witgoArgs)) }\n", len(fn.Params), "host import "+imported.callName+"#"+fn.Name+" received %d arguments")
			args := make([]string, 0, len(fn.Params))
			for index, param := range fn.Params {
				name := fmt.Sprintf("_witgoArg%d", index)
				fmt.Fprintf(&r.out, "\t\t\t\t%s, err := liftValue[%s](_witgoArgs[%d])\n", name, r.goType(param.Type), index)
				fmt.Fprintln(&r.out, "\t\t\t\tif err != nil { return nil, err }")
				args = append(args, name)
			}
			call := host + "." + goName(fn.Name) + "(" + strings.Join(args, ", ") + ")"
			if fn.Result == nil {
				fmt.Fprintf(&r.out, "\t\t\t\t%s\n\t\t\t\treturn nil, nil\n", call)
			} else {
				fmt.Fprintf(&r.out, "\t\t\t\treturn %s, nil\n", call)
			}
			fmt.Fprintln(&r.out, "\t\t\t},")
			fmt.Fprintln(&r.out, "\t\t},")
		}
	}
	fmt.Fprintln(&r.out, "\t}")
}

type worldInterface struct {
	name          string
	interfaceName string
	callName      string
	functions     []*ir.Func
}

func (w worldInterface) clientName(worldName string) string {
	return goLocalName(worldName + "-" + w.name + "-client")
}

func (r *renderer) importParams(imports []worldInterface) string {
	var params []string
	for _, imported := range imports {
		params = append(params, goLocalName(imported.name)+" "+imported.interfaceName)
	}
	if len(params) == 0 {
		return ""
	}
	return ", " + strings.Join(params, ", ")
}

func (r *renderer) importArgs(imports []worldInterface) string {
	var args []string
	for _, imported := range imports {
		args = append(args, goLocalName(imported.name))
	}
	if len(args) == 0 {
		return ""
	}
	return ", " + strings.Join(args, ", ")
}

func (r *renderer) worldParts(world *ir.World) ([]worldInterface, []worldInterface, []*ir.Func, error) {
	var imports []worldInterface
	var exports []worldInterface
	var direct []*ir.Func
	for _, item := range world.Items {
		switch item := item.(type) {
		case *ir.Import:
			resolved, err := r.resolveExtern(item.Name, item.Extern)
			if err != nil {
				return nil, nil, nil, fmt.Errorf("world %q import %q: %w", world.Name, item.Name, err)
			}
			imports = append(imports, resolved)
		case *ir.Export:
			resolved, err := r.resolveExtern(item.Name, item.Extern)
			if err != nil {
				return nil, nil, nil, fmt.Errorf("world %q export %q: %w", world.Name, item.Name, err)
			}
			exports = append(exports, resolved)
		case *ir.Func:
			direct = append(direct, item)
		case *ir.Use, *ir.Include, *ir.TypeDef, *ir.Record, *ir.Flags, *ir.Enum, *ir.Variant, *ir.Resource:
		default:
			return nil, nil, nil, fmt.Errorf("world %q: unsupported item %T", world.Name, item)
		}
	}
	return imports, exports, direct, nil
}

func (r *renderer) resolveExtern(name string, extern ir.ExternType) (worldInterface, error) {
	switch extern := extern.(type) {
	case *ir.ExternPath:
		if len(extern.Path.Segments) == 0 {
			return worldInterface{}, fmt.Errorf("empty interface path")
		}
		pathName := extern.Path.Segments[len(extern.Path.Segments)-1]
		iface, ok := r.interfaces[pathName]
		if !ok {
			return worldInterface{}, fmt.Errorf("interface %q was not found", pathName)
		}
		return worldInterface{
			name:          name,
			interfaceName: goName(pathName),
			callName:      r.interfaceID(pathName),
			functions:     interfaceFunctions(iface.Items),
		}, nil
	case *ir.InlineInterface:
		interfaceName := goName(name)
		if err := r.renderInterface(interfaceName, extern.Items); err != nil {
			return worldInterface{}, err
		}
		return worldInterface{
			name:          name,
			interfaceName: interfaceName,
			callName:      r.interfaceID(name),
			functions:     interfaceFunctions(extern.Items),
		}, nil
	case *ir.FuncType:
		interfaceName := goName(name)
		items := []ir.InterfaceItem{extern.Func}
		if err := r.renderInterface(interfaceName, items); err != nil {
			return worldInterface{}, err
		}
		return worldInterface{
			name:          name,
			interfaceName: interfaceName,
			callName:      "",
			functions:     []*ir.Func{extern.Func},
		}, nil
	default:
		return worldInterface{}, fmt.Errorf("unsupported extern type %T", extern)
	}
}

func interfaceFunctions(items []ir.InterfaceItem) []*ir.Func {
	var functions []*ir.Func
	for _, item := range items {
		if fn, ok := item.(*ir.Func); ok {
			functions = append(functions, fn)
		}
	}
	return functions
}

func (r *renderer) renderClientMethod(worldName, interfaceName string, fn *ir.Func) error {
	fmt.Fprintf(&r.out, "func (c *%s) %s%s {\n", worldName, goName(fn.Name), r.clientSignature(fn))
	args := make([]string, 0, len(fn.Params))
	for index, param := range fn.Params {
		name := paramName(param, index)
		args = append(args, r.lowerExpr(name, param.Type))
	}
	callName := fn.Name
	if interfaceName != "" {
		callName = interfaceName + "#" + fn.Name
	}
	if fn.Result == nil {
		fmt.Fprintf(&r.out, "\t_, err := c.runtime.Call(%s", strconv.Quote(callName))
		for _, arg := range args {
			fmt.Fprintf(&r.out, ", %s", arg)
		}
		fmt.Fprintln(&r.out, ")")
		fmt.Fprintln(&r.out, "\treturn err")
		fmt.Fprintln(&r.out, "}")
		fmt.Fprintln(&r.out)
		return nil
	}

	fmt.Fprintf(&r.out, "\tvalue, err := c.runtime.Call(%s", strconv.Quote(callName))
	for _, arg := range args {
		fmt.Fprintf(&r.out, ", %s", arg)
	}
	fmt.Fprintln(&r.out, ")")
	fmt.Fprintf(&r.out, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", r.zeroValue(fn.Result))
	fmt.Fprintf(&r.out, "\tresult, err := %s\n", r.liftRuntimeExpr("c.runtime", "value", fn.Result))
	fmt.Fprintf(&r.out, "\tif err != nil {\n\t\treturn %s, fmt.Errorf(%q, err)\n\t}\n", r.zeroValue(fn.Result), "call "+callName+": %w")
	if named, ok := fn.Result.(*ir.NamedType); ok && len(r.modelFuncs[named.Name]) > 0 {
		fmt.Fprintln(&r.out, "\tresult.binding = c")
	}
	fmt.Fprintln(&r.out, "\treturn result, nil")
	fmt.Fprintln(&r.out, "}")
	fmt.Fprintln(&r.out)
	return nil
}

func (r *renderer) contractSignature(fn *ir.Func) string {
	params := r.params(fn.Params)
	if fn.Result == nil {
		return "(" + params + ")"
	}
	return "(" + params + ") " + r.goType(fn.Result)
}

func (r *renderer) clientSignature(fn *ir.Func) string {
	params := r.params(fn.Params)
	if fn.Result == nil {
		return "(" + params + ") error"
	}
	return "(" + params + ") (" + r.goType(fn.Result) + ", error)"
}

func (r *renderer) modelSignature(fn *ir.Func) string {
	params := r.params(fn.Params[1:])
	if fn.Result == nil {
		return "(" + params + ") error"
	}
	return "(" + params + ") (" + r.goType(fn.Result) + ", error)"
}

func (r *renderer) params(params []ir.Param) string {
	out := make([]string, 0, len(params))
	for index, param := range params {
		out = append(out, paramName(param, index)+" "+r.goType(param.Type))
	}
	return strings.Join(out, ", ")
}

func paramName(param ir.Param, index int) string {
	if param.Name == "" || param.Name == "self" {
		return fmt.Sprintf("arg%d", index)
	}
	return goLocalName(param.Name)
}

func modelMethodName(recordName, functionName string) string {
	method := goName(functionName)
	record := goName(recordName)
	if strings.HasSuffix(method, record) && len(method) > len(record) {
		return strings.TrimSuffix(method, record)
	}
	return method
}

func (r *renderer) goType(typ ir.Type) string {
	switch typ := typ.(type) {
	case nil:
		return "any"
	case *ir.PrimitiveType:
		if mapped, ok := primitiveType(typ.Name); ok {
			return mapped
		}
		return "any"
	case *ir.NamedType:
		if typ.Wildcard {
			return "any"
		}
		if mapped, ok := primitiveType(typ.Name); ok {
			return mapped
		}
		return goName(typ.Name)
	case *ir.GenericType:
		switch typ.Name {
		case "list":
			return "[]" + r.goType(firstType(typ.Args))
		case "option":
			return "*" + r.goType(firstType(typ.Args))
		case "borrow", "own":
			return r.goType(firstType(typ.Args))
		case "map":
			if len(typ.Args) == 2 {
				return "map[" + r.goType(typ.Args[0]) + "]" + r.goType(typ.Args[1])
			}
		case "result":
			r.hasResult = true
			if len(typ.Args) == 2 {
				return "Result[" + r.goType(typ.Args[0]) + ", " + r.goType(typ.Args[1]) + "]"
			}
		}
		args := make([]string, 0, len(typ.Args))
		for _, arg := range typ.Args {
			args = append(args, r.goType(arg))
		}
		return goName(typ.Name) + "[" + strings.Join(args, ", ") + "]"
	case *ir.TupleType:
		var fields []string
		for index, item := range typ.Items {
			fields = append(fields, fmt.Sprintf("V%d %s", index, r.goType(item)))
		}
		return "struct { " + strings.Join(fields, "; ") + " }"
	default:
		return "any"
	}
}

func (r *renderer) lowerExpr(expression string, typ ir.Type) string {
	return expression
}

func (r *renderer) liftExpr(expression string, typ ir.Type) string {
	return "liftValue[" + r.goType(typ) + "](" + expression + ")"
}

func (r *renderer) liftRuntimeExpr(runtime, expression string, typ ir.Type) string {
	return r.liftExpr(expression, typ)
}

func (r *renderer) zeroValue(typ ir.Type) string {
	return "*new(" + r.goType(typ) + ")"
}

func primitiveType(name string) (string, bool) {
	types := map[string]string{
		"bool": "bool", "char": "rune", "string": "string",
		"u8": "uint8", "u16": "uint16", "u32": "uint32", "u64": "uint64",
		"s8": "int8", "s16": "int16", "s32": "int32", "s64": "int64",
		"f32": "float32", "f64": "float64",
	}
	result, ok := types[name]
	return result, ok
}

func (r *renderer) interfaceID(name string) string {
	if r.witPackage == nil {
		return name
	}
	id := r.witPackage.Namespace + ":" + r.witPackage.Name + "/" + name
	if r.witPackage.Version != "" {
		id += "@" + r.witPackage.Version
	}
	return id
}

func witPackageID(witPackage *ir.Package) string {
	if witPackage == nil {
		return ""
	}
	id := witPackage.Namespace + ":" + witPackage.Name
	if witPackage.Version != "" {
		id += "@" + witPackage.Version
	}
	return id
}

func goPackageName(name string) string {
	var out strings.Builder
	for _, char := range strings.ToLower(name) {
		if unicode.IsLetter(char) || unicode.IsDigit(char) || char == '_' {
			out.WriteRune(char)
		} else {
			out.WriteRune('_')
		}
	}
	result := strings.Trim(out.String(), "_")
	if result == "" || unicode.IsDigit([]rune(result)[0]) || goKeywords[result] {
		return "wit_" + result
	}
	return result
}

func firstType(types []ir.Type) ir.Type {
	if len(types) == 0 {
		return nil
	}
	return types[0]
}

func isPackageName(name string) bool {
	if name == "" {
		return false
	}
	for index, char := range name {
		if index == 0 && !unicode.IsLetter(char) && char != '_' {
			return false
		}
		if index > 0 && !unicode.IsLetter(char) && !unicode.IsDigit(char) && char != '_' {
			return false
		}
	}
	return !goKeywords[name]
}

func goName(name string) string {
	words := strings.FieldsFunc(name, func(char rune) bool {
		return char == '-' || char == '_' || unicode.IsSpace(char)
	})
	for index, word := range words {
		lower := strings.ToLower(word)
		if initialisms[lower] {
			words[index] = strings.ToUpper(lower)
			continue
		}
		runes := []rune(word)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		words[index] = string(runes)
	}
	result := strings.Join(words, "")
	if result == "" {
		return "Value"
	}
	if unicode.IsDigit([]rune(result)[0]) {
		result = "Value" + result
	}
	return result
}

func goLocalName(name string) string {
	exported := goName(name)
	if initialisms[strings.ToLower(exported)] {
		return strings.ToLower(exported)
	}
	runes := []rune(exported)
	runes[0] = unicode.ToLower(runes[0])
	result := string(runes)
	if goKeywords[result] {
		return result + "Value"
	}
	return result
}

var initialisms = map[string]bool{
	"api": true, "http": true, "https": true, "id": true, "ip": true,
	"json": true, "sql": true, "sso": true, "tcp": true, "udp": true,
	"uri": true, "url": true, "uuid": true, "xml": true,
}

var goKeywords = map[string]bool{
	"break": true, "default": true, "func": true, "interface": true,
	"select": true, "case": true, "defer": true, "go": true, "map": true,
	"struct": true, "chan": true, "else": true, "goto": true, "package": true,
	"switch": true, "const": true, "fallthrough": true, "if": true,
	"range": true, "type": true, "continue": true, "for": true,
	"import": true, "return": true, "var": true,
}
