package witgo

import (
	"errors"
	"fmt"
)

var ErrResultTooLarge = errors.New("WebAssembly result exceeds configured limit")

// ReadMemory is unavailable for Component Model values. It remains only to
// produce a clear migration error for code generated by older witgo releases.
func (r *Runtime) ReadMemory(offset, length uint32) ([]byte, error) {
	return nil, fmt.Errorf("ReadMemory is a core-Wasm ABI operation; regenerate bindings for the Component Model runtime")
}
